### ISSUE TITLE
Power as an entity

### ISSUE THREAD

**Issue by Dizzyikea** [krahabb/meross_lan#1]
Firstly thank you for this once i got the MQTT stuff done this bit was simple 3 MS310's working perfectly

Is it possible to have the the power, energy, voltage and current as entities?

I could do this as a template i guess something like this

  - platform: template
    sensors:
      Meross_Plug_Watts:
        friendly_name: "Dehumidifier Power"
        icon_template: mdi:air-filter
        unit_of_measurement: "w"
        value_template: '{% if states.switch.Meross_lanxxxxxxxx %}{{ states.switch.Meross_lanxxxxxxxx.attributes.current_power_w }}{% else %}Off{% endif %}'

I think it would be much nicer to have 5 entities per device

**Comment by krahabb** [comment]
First of all, thank you for your comment, I'm happy this is useful to others (that's the idea of sharing software!)

Your request was something I was thinking about too but I was too lazy to implement it in the first rush.
I'm thinking about letting the user choose during the device configuration phase if those sensors should be added or not and I think I can work on it in the coming days so you can expect a quick update.
If there's any idea about this feature I would be happy to know so to think about a better/useful implementation of it

**Comment by almico** [comment]
@krahabb I just completed testing your component with my MSS310H and it works! (Thank you for your work!)
The first thing I noticed was the lack of V, A, W and the likes and came to GitHub to open an issue, just to discover this one that made me notice that data was already available, but in a slightly less immediate way.
All the other power plugs I have in HA use the entity approach, thus it would be extremely helpful.

**Comment by krahabb** [comment]
Yeah,
I've worked on it and it's almost done but I had a couple of days off..
I hope to publish all in the coming days....
Thank you for your comment!

**Comment by Dizzyikea** [comment]
![image](https://user-images.githubusercontent.com/36666298/112053686-8cbe7700-8b4c-11eb-8c89-c566235d37f8.png)

FYI works fine as a template too :)

**Comment by krahabb** [comment]
I've refactored the code to expose sensors instead of 'attrs' for power, energy, voltage, current
This will probably break your templates and that might be a bit rude but I wanted to keep it simple and efficient so to avoid posting unnecessary state updates to the switch entity when the component publishes new energy and power data (which happens quite often)
I think this is better sooner than later.

**Comment by Dizzyikea** [comment]
Not rude at all, fantastic i'll test

**Comment by Dizzyikea** [comment]
Well mixed results

The entities seem to work just fine but

2 of my 3 devices seems to want to show as one?
![image](https://user-images.githubusercontent.com/36666298/112155442-36e5df80-8bdd-11eb-81ee-844ebcbaf949.png)

![image](https://user-images.githubusercontent.com/36666298/112155667-6b599b80-8bdd-11eb-86f6-b36c2ef71397.png)

![image](https://user-images.githubusercontent.com/36666298/112155818-9643ef80-8bdd-11eb-8b11-ebd2dc10bc99.png)


They show separately on the integration tab

**Comment by almico** [comment]
What is the correct way to upgrade (I installed using HACS), test and report back?

**Comment by almico** [comment]
Well... I just upgraded via HACS, restarted HA and off we go again 🥰 
![image](https://user-images.githubusercontent.com/15247405/112163390-453bf780-8bed-11eb-84c4-5974b88294b4.png)
Thank you!

**Comment by krahabb** [comment]
> Well mixed results
> 
> The entities seem to work just fine but
> 
> 2 of my 3 devices seems to want to show as one?
> ![image](https://user-images.githubusercontent.com/36666298/112155442-36e5df80-8bdd-11eb-81ee-844ebcbaf949.png)
> 
> ![image](https://user-images.githubusercontent.com/36666298/112155667-6b599b80-8bdd-11eb-86f6-b36c2ef71397.png)
> 
> ![image](https://user-images.githubusercontent.com/36666298/112155818-9643ef80-8bdd-11eb-8b11-ebd2dc10bc99.png)
> 
> 
> They show separately on the integration tab
> 
> 

It happened to me too and I thought it was related to #8. After the patch it still merged the devices...
In the end I've removed and reconfigured all devices even if it shouldnt be needed in theory since the patch (hardware mac) should work on previously configured devices by just reloading the entry configuration
