### ISSUE TITLE
Automatic removal of stale devices

### ISSUE THREAD

**Issue by wsw70** [krahabb/meross_lan#10]
**Is your feature request related to a problem? Please describe.**

Plugs and strips come and go - they are sometimes connected and sometimes not. Unfortunately, once they are configured they stay in the system for good.

**Describe the solution you'd like**

A periodic check for devices that are offline for an extended time (say, an hour). These devices could be removed, and then advertise as new devices once they are plugged back.

**Comment by almico** [comment]
I would prefer a way to manually, and consciously, remove them rather than see them disappear automatically.

**Comment by wsw70** [comment]
> I would prefer a way to manually, and consciously, remove them rather than see them disappear automatically.

That could be an option. The feature is useful when the population of the plugs is "dynamic".

**Comment by krahabb** [comment]
This is though
removing stale entries would require reconfiguring them once reconnected. I'm trying to figure out if I can 'disable' them (in HA terms) so to still have the entities internally configured but just disappearing from the UI and recorder so once reconnected and alive they will appear where they were left.

**Comment by krahabb** [comment]
I've tried to disable the 'ConfigEntry' when the device becomes stale but it messed up everything (I guess this feature of HA is too new to work consistently or, more likely, I didn't properly get how it works)
I'm going to publish a new release without this one since I prefer to keep things going introducing bulb support and protocol key configuration for devices.
This 'stale removal' feature is still in the queue though. Any help or hint highly appreciated!
I'm still in the mood of not completely removing config entries for stale devices since it would require a manual reconfiguration step every time you replug your items.
I guess @wsw70 request is related to not having devices and entities polluting the UI with 'unavailable states' when these could be offline for extended periods of time and I see the point: that's why I'm keeping this up and trying to figure out how to automatically disable devices so they disapper from UI but still they are left in HA configuration in order to be quickly revived when coming back online

**Comment by wsw70** [comment]
Thanks @krahabb for the effort. 

Yes, my point was as described in your last paragraph. I will have a look on my side as well.

Maybe you could tag the issue with 'enhancement' and 'sleeping' or something, to show that there is still hope :) (as opposed to closing it)

**Comment by wsw70** [comment]
> I'm still in the mood of not completely removing config entries for stale devices since it would require a manual reconfiguration step every time you replug your items.

Maybe that this could be configurable? My idea was that a device that is not used for some time is expected to be rediscovered and reconfigured. But again, this is my own idea of how plugs work.

I will update my repo to point to yours and dig in your code (I am a poor developer, though)

**Comment by wsw70** [comment]
> I'm still in the mood of not completely removing config entries for stale devices since it would require a manual reconfiguration step every time you replug your items.

At least as an option that would be useful: you unplug a plug, which means you usually do not need it anymore where it was. 

It makes then sense to completely remove it so once you plug it back in, it is rediscovered and can be reconfigured to the new place where it is used.

**Comment by nao-pon** [comment]
My usage is that the plug power is turned off at night.  I'm hoping that this feature will be selectable as I don't want to have to re-register if the power is lost.

**Comment by nao-pon** [comment]
In this regard, it would be nice to have the option to be notified offline on HA when the meross device goes offline.

**Comment by almico** [comment]
> you unplug a plug, which means you usually do not need it anymore where it was

I have Node-red flows that monitor low power usage for a user-configurable amount of time and that's published to an entity that's accessible to HA. One of the things I would appreciate the least is something that automatically deletes an entity 😄

**Comment by wsw70** [comment]
@almico @nao-pon  : OK, I give up :)

I probably have a workflow that is different from others, where I use some of the plugs for a limited time only (or move them) and therefore I do not want to have a bunch of them as "unavailable".

But this will not stop me from moving to @krahabb integration :)

I will manage the removal of stale plugs independently, from `pyscript` and everyone will be happy.

**Comment by nao-pon** [comment]
@wsw70 I think you don't have to give up. @krahabb seems to be positively starting the implementation. I think it would be best for everyone if the configuration flows could allow the user to select this feature.

**Comment by wsw70** [comment]
@nao-pon : my comment was really tongue in cheek :) 

The integration is great (I just pushed everyone using mine to go here: https://github.com/wsw70/meross-local-mqtt) and my usecase is probably  very niche (I am actually surprised how much it is). I will find an independent way to clean up (other stale entities as well BTW) so no worries.

In any case this certainly needs to be opt-in.
