### ISSUE TITLE
MSH300 connection loss

### ISSUE THREAD

**Issue by shra1976** [krahabb/meross_lan#108]
I have the following problem: when the connection losses, my MSH300 begin flashing and it can't reconnect to Mosquitto broker. I see it connected in the LAN but not to the MQTT broker. Does anyone experienced the same issue and found a solution?

**Comment by krahabb** [comment]
Hello @shra1976,
Every Meross device has 2 mqtt brokers configured (primary and secondary) and it should keep switching between the two when any fails. But, in some user experiences, when the primary fails and the second is not configured, it looks like it 'stalls' the switching algorithm (or kind of).
That's why, when configuring for a private mqtt broker, the usual utilities (like the @bytespider one) allow you to configure both the primary and secondary.
By setting both the mqtt primary and secondary brokers to the same address, the device usually works consistently by keeping retrying to connect to the same one.
If I'm not wrong, the latest versions of the @bytespider utility automatically sets both the addresses to the one you configure as (primary) mqtt broker but if you used an older version, the secondary would be empty and so you need to fix this.

**Comment by bytespider** [comment]
@krahabb you are correct, the latest version will set both addresses to the primary one if only one is provided

**Comment by bytespider** [comment]
@shra1976 have you recently upgraded your broker, say From Home Assistant Mosquitto addon 5.x to 6.x?

**Comment by shra1976** [comment]
Hello @krahabb thank you for your help. Probably I've set only the primary broker. I used the android app made by Alberto Geniola (the first issue). Now I tried with the latest version of the @bytespider utility but I can't connect to my MQTT broker. I have a Mosquitto broker version 1.6.12. The mosquitto configuration is:
`port 8883
require_certificate false
allow_anonymous true
cafile /etc/mosquitto/certs/mqtt_ca.crt
certfile /etc/mosquitto/certs/mqtt.crt
keyfile /etc/mosquitto/certs/mqtt.key
connection_messages true
log_type all
log_dest stdout
`
It works with other MQTT devices but MSH300 doesn't connect to it... where am I wrong?

**Comment by bytespider** [comment]
@shra1976 let me get the facts correct:
You are running vanilla Mosquitto 1.6.12 (not via Home Assistant)
The device connects to your LAN but not the broker

Questions:
What messages, if any, are displayed from your broker when the device tries to connect?
Do devices have access to the internet?

**Comment by override80** [comment]
In my case, the msh300 does connect to the wifi and to the MQTT broker. I see messages being published:

`/appliance/2108317438792926281348e1e974d3be/publish {"header":{"messageId":"668a11b610af0e18f640c80b1e9b304c","namespace":"Appliance.Control.Bind","method":"SET","payloadVersion":1,"from":"/appliance/2108317438792926281348e1e974d3be/subscribe","timestamp":1636892671,"timestampMs":788,"sign":"ea1651217b48e62892237f8db23a8a9a"},"payload":{"bind":{"bindTime":1636892671,"time":{"timestamp":1636892671,"timezone":"","timeRule":[]},"hardware":{"type":"msh300hk","subType":"un","version":"4.0.0","chipType":"MT7686","uuid":"2108317438792926281348e1e974d3be","macAddress":"48:e1:e9:74:d3:be"},"firmware":{"version":"4.1.24","homekitVersion":"4.1","compileTime":"2021/08/23 14:58:32 GMT +08:00","encrypt":1,"wifiMac":"46:d9:e7:d7:b7:08","innerIp":"10.11.12.172","server":"10.11.12.98","port":8883,"userId":0}}}}
/appliance/2108317438792926281348e1e974d3be/subscribe {"header": {"messageId": "5787d43f9df741a49a120362ff53d286", "namespace": "Appliance.Hub.Sensor.All", "method": "GET", "payloadVersion": 1, "from": "/appliance/2108317438792926281348e1e974d3be/publish", "timestamp": 1636892675, "timestampMs": 0, "sign": "2724ba68ba6bc4986c571c0696f59151"}, "payload": {"all": []}}
/appliance/2108317438792926281348e1e974d3be/subscribe {"header": {"messageId": "62d5b4e4a9264e349c47851e7ca55acb", "namespace": "Appliance.Hub.Mts100.All", "method": "GET", "payloadVersion": 1, "from": "/appliance/2108317438792926281348e1e974d3be/publish", "timestamp": 1636892675, "timestampMs": 0, "sign": "31eb8944a0f2ea56757e523a5367336f"}, "payload": {"all": []}}
/appliance/2108317438792926281348e1e974d3be/subscribe {"header": {"messageId": "ae576028843140e5a86b455385723c86", "namespace": "Appliance.Hub.Battery", "method": "GET", "payloadVersion": 1, "from": "/appliance/2108317438792926281348e1e974d3be/publish", "timestamp": 1636892675, "timestampMs": 0, "sign": "40ae5e47bf2e7a2ee84a20b9763cbe62"}, "payload": {"battery": []}}
`

But the green light keeps blicking on the hub and I cannot pair the valves (MTS150). The Wifi icon on the valve itself keeps blinking as well :/ Well i tried double tapping on the hub, i read this is the way to pair those to the bub. 

I have internet connection as well

**Comment by bytespider** [comment]
@override80 do you allow the device to connect to the internet?

**Comment by override80** [comment]
@bytespider I do, in the DHCP settings of my DHCP server I provided my ISP router as a gateway (it has no firewall rules).

**Comment by bytespider** [comment]
@override80 are you in a position to try this experimental branch? I watched the pairing process of the Official App and noticed they send over some time information. https://github.com/bytespider/Meross/tree/feature/network-time

**Comment by override80** [comment]
Yes, of coruse, I did, but I cannot execute the command successfully anymore:

`$ ./meross setup --gateway 10.10.10.1 --wifi-ssid FightClub --wifi-pass .FC-891115 --mqtt mqtts://10.11.12.98 
Setting up device with IP 10.10.10.1
┌───────────────────────────────────────────────────┬─────────────────────────────────────────┐
│Primary MQTT broker                                │10.11.12.98:8883                         │
├───────────────────────────────────────────────────┼─────────────────────────────────────────┤
│Failover MQTT broker                               │10.11.12.98:8883                         │
└───────────────────────────────────────────────────┴─────────────────────────────────────────┘
Error Unable to connect to device
Error Unable to connect to device
Setting up device timezone Europe/Rome
Error Unable to connect to device
Setting up device wifi
Error Unable to connect to device
Device will reboot...
`

If i check out master, this is the result:

`$ ./meross setup --gateway 10.10.10.1 --wifi-ssid FightClub --wifi-pass .FC-891115 --mqtt mqtts://10.11.12.98 
Setting up device with IP 10.10.10.1
┌───────────────────────────────────────────────────┬─────────────────────────────────────────┐
│Primary MQTT broker                                │10.11.12.98:8883                         │
├───────────────────────────────────────────────────┼─────────────────────────────────────────┤
│Failover MQTT broker                               │10.11.12.98:8883                         │
└───────────────────────────────────────────────────┴─────────────────────────────────────────┘
┌────────────────────┬────────────────────────────────────────────────────────────────────────┐
│Device              │msh300hk un MT7686 (hardware:4.0.0 firmware:4.1.24)                     │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│UUID                │2108317438792926281348e1e974d3be                                        │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│Mac address         │48:e1:e9:74:d3:be                                                       │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│IP address          │                                                                        │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│Current MQTT broker │10.11.12.98:8883                                                        │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│Credentials         │User: 48:e1:e9:74:d3:be                                                 │
│                    │Password: 0_5c0c6e167a67fdef302cce33457bc54d                            │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│MQTT topics         │Publishes to: /appliance/2108317438792926281348e1e974d3be/publish       │
│                    │Subscribes to: /appliance/2108317438792926281348e1e974d3be/subscribe    │
└────────────────────┴────────────────────────────────────────────────────────────────────────┘
Device will reboot...
`

**Comment by krahabb** [comment]
@override80 ,
The previous successful MQTT log states everything was (and maybe still can be) good with MSH300 on MQTT and maybe the issue with the beta from @bytespider is something related to this new feature he's trying to implement.
The hub led blinking could definitely be the pairing with the MTS150 which is not working reliably. I remember I had issues with my MTS100 for the same process and had to reboot/restart the valves different times in order to get it right

**Comment by krahabb** [comment]
@shra1976 ,
From your first message I guess the MSH300 was likely working on MQTT except when losing connection for whatever reason and not being able to reconnect. If this is the case then your MQTT setup should be fine and I'd keep investigating the MSH300 setup/configuration.
If it 'never' worked i.e. you never had a successfull meross topic broadcast over mqtt then I'll suggest you to check https://github.com/krahabb/meross_lan/wiki/Mosquitto-Mon-Amour .
If we're in this scenario the problem could lie in MQTT authentication. From your comment I don't see any password file or authentication configuration in your mosquitto and this should or could be good but... maybe there's something else 'hidden'
My wiki tries to sort out the mosquitto configuration process and that could provide you some hints

**Comment by override80** [comment]
Hi @krahabb it's definitively as you said. I tried installing the Meross official app and setting up the MSH300 - it all went through smoothly BUT there is no way i can pair the valve with the hub. I've tried the whole +/- reset stuff 10 times, doble tapping the button on the hub at different times, changing batteries, bringing the hub closer etc... They do not pair. At this point I'm starting to think that the hub might be having some issues, I'll simply return it...

**Comment by bytespider** [comment]
> @bytespider Yes, of coruse, I did, but I cannot execute the command successfully anymore:
Thanks for trying. I was hoping that if it was a time related issue it could be resolved by telling the device what the current timezone should be. Granted only have a limited sample set (2 x MSS310)

@override80 if you cant get it working with the official app then I would agree there is an issue with the device/s

**Comment by shra1976** [comment]
Finally solved! I was wrong using mqtts protocol. With mqtt:// it works and I can connect to my broker. Thanks for the help!

**Comment by krahabb** [comment]
Awesome!
