### ISSUE TITLE
Update broken link in wiki

### ISSUE THREAD

**Issue by bytespider** [krahabb/meross_lan#113]
## Version of the custom_component
N/A

## Configuration
N/A

## Describe the bug
In the [wiki](https://github.com/krahabb/meross_lan/wiki/Mosquitto-Mon-Amour#issues) you link to a deleted branch. I would be better to link to the repo or the upstream where the original branch have now been merged.
Upstream (and the one Home Assistant uses): https://github.com/pvizeli/mosquitto-auth-plug

## Debug log
N/A

**Comment by krahabb** [comment]
Thank you @bytespider ! (fixed)
