### ISSUE TITLE
Sockets not communicating anymore with HA: "detail:  sign error"

### ISSUE THREAD

**Issue by homonto** [krahabb/meross_lan#116]
So all my sockets were working fine until today they starated one by one being "unavailable"
I have done repairing again with my MQTT as per documenation:

`sudo ./meross-setup --gateway 10.10.10.1 --wifi-ssid BT-gowno --wifi-pass mypass --mqtt mqtt://my_IP:8883`

and from MQTT explorer I can see:

`{"header":{"messageId":"12f52c6ed36e46939b76128c2fb6e598","namespace":"Appliance.System.All","method":"ERROR","payloadVersion":1,"from":"/appliance/2102256513344551805548e1e94e3fb1/publish","timestamp":1637193306,"timestampMs":845,"sign":"70be4fe9ea272f3ae135666850af046e"},"payload":{"error":{"code":5001,"detail":"sign error"}}}`

I'm astonished by loosing all my sockets at once - funny thing: out of 12, few are still alive but half is not manageable anymore

Any idea what has happened?

thank you

**Comment by homonto** [comment]
hmm, working now - probably it does not like to work in the night - I will test further so not closing yet ;-)

**Comment by krahabb** [comment]
Hello @homonto , sorry for the late reply...I was trying to figure out a possible reason for this and nothing came to mind.

The only thing I could think of is that maybe there's a bug in (meross_lan) code and it starts 'failing' message signatures once a specific (unknown at the moment) event occurs. I'll review the signing algorithm to see if there's something very hidden that could rarely occur.

**Comment by homonto** [comment]
thank you @krahabb for your answer
so out of 12 sockets, few had few fields "unavailable" (other fields reporting OK), some had no connection to HA at all (grey switch). Seriously I have no idea what happened that all are ok now - 2 of them I "re-connected" using Linux script as they were not able to come back to full life - others came by themselves 
magic...
No changes on HA though - then I reconfigured all of them to be "auto" and 5s
at this moment of time all are OK

one more thing: since last HA upgrade, there is 1 more switch, to turn ON/OFF the LED on the socket - but some were saying it is to lock/unlock manual switch - no, it is not - it only turns ON/OFF LED

see example:
![Screenshot 2021-11-19 at 13 20 51](https://user-images.githubusercontent.com/46562447/142629555-2f95e52a-3bb2-407a-b247-05742d1ab544.jpg)


btw I have 12 Tuya and 12 Meross sockets at home - my life is fully dependent on the HA now so I need them all working ;-)

**Comment by krahabb** [comment]
Hello @homonto ,
the switch itself is to control the 'do not disturb' function of the device which is usually associated to the device 'self illumination'
so when you turn on the switch the device goes in do not disturb mode i.e. it disables its presence light
I'm refactoring a bit this entity/feature in the next release but still it controls the DND mode of the device

I've also refactored a bit the 'sign error' management in order to make it more robust. Let's see if it improves reliability overall

**Comment by homonto** [comment]
> Hello @homonto , the switch itself is to control the 'do not disturb' function of the device which is usually associated to the device 'self illumination' so when you turn on the switch the device goes in do not disturb mode i.e. it disables its presence light I'm refactoring a bit this entity/feature in the next release but still it controls the DND mode of the device
> 
> I've also refactored a bit the 'sign error' management in order to make it more robust. Let's see if it improves reliability overall

that is correct - not "parental control" as one could think ;-)
btw it is useful if you want to turn OFF LED for the night but it can be confusing if someone sees... nothing he might think the socket is not working anymore ;-)

**Comment by krahabb** [comment]
Hello @homonto,
I've just published a pre-release (soon to be converted to 'official') where there are some improvements on the connection issues and the DND-Light has been changed to a 'real' light with inverted logic with respect to the previous 'switch' implementation.

If you can manage to check/test it and report if there are improvements that would really help in figuring out the current 'state of the art' with these issues

Thank you a lot!

**Comment by homonto** [comment]
> Hello @homonto, I've just published a pre-release (soon to be converted to 'official') where there are some improvements on the connection issues and the DND-Light has been changed to a 'real' light with inverted logic with respect to the previous 'switch' implementation.
> 
> If you can manage to check/test it and report if there are improvements that would really help in figuring out the current 'state of the art' with these issues
> 
> Thank you a lot!

happy to do it @krahabb  but please drive me how to get the "pre-release" version installed on my HA

**Comment by krahabb** [comment]
Oh well..
I remember there was an option in HACS to show you also beta versions releases in UI but I can't really find it anymore :(
If you go to the HACS panel and/or integrations under HACS itself maybe the upper right burger menu will give you some hints.
Or just try to 'update informations' for the meross_lan repo

I'm really sorry...my HACS installed on different development machines and the production one too already show me the 'pre-release' version but I can't really find how to enable/disable this feature

**Comment by homonto** [comment]
2.4?
![Screenshot 2021-11-26 at 09 56 33](https://user-images.githubusercontent.com/46562447/143562339-938129b9-6b89-455b-bf94-eeb4f0463017.jpg)

**Comment by homonto** [comment]
I installed 2.4 beta and it works (gimme some time to test all of them)
however, I have 1 comment: DND mode when ON should turn LED OFF - now it is opposite: when DND is ON LED is also ON
so either you change to inverted or call it i.e. "LED indicator" instead of DND
my logic is:
- if the name is: "DND" then if ON make the LED off
- if the name is "LED" then if ON make the LED on
what do you think?

![Screenshot 2021-11-26 at 10 18 28](https://user-images.githubusercontent.com/46562447/143565554-f3a36c4b-24d1-44ef-a747-535ef3ae203d.jpg)

**Comment by krahabb** [comment]
Yeah..I totally agree it's still confusing....

Let's see maybe other comments and I'll try to summ it up to a reasonable end.
I could add options in configuration in order for the user to choose either switch/light and direct/inverted logic but it seems too much for a really 'poor' feature

**Comment by homonto** [comment]
honestly it does not bother me - I renamed them anyway to my needs ;-)
btw I am not 100% sure how useful this is (turning LED off) because when someone sees "OFF" he might press it to turn the socket ON while it was already ON so the press would ... turn it OFF - imagine your server is connected to it... ;-)

**Comment by homonto** [comment]
hi @krahabb I see you pushed 2.4.1 - is it the same I was just testing as beta?

**Comment by krahabb** [comment]
More or less :)
2.4.1 adds mainly a fix for device timestamp and timezone settings where used (depends on how your devices work on your lan and which devices you have to be useful)

I'm anyway working on some other patches at the moment, not relevant to the majority of the users but something could still come in and I expect to release a more updated version soon...

so no rush for 'Rush' :)
