### ISSUE TITLE
mss210 client connection error in async_http_request

### ISSUE THREAD

**Issue by patrick-blom** [krahabb/meross_lan#117]
Hi, 
I have a problem with the current version of the component in combination with the device type mss210. Some context; I'm using around 20 different Meross / Refoss devices. Most devices are mss210, some mss310 / mss710 / msl120 and some are msl420 table lights. I'm a new component user. I switched from meross-homeassistant component to these component because of some problems with the current Home Assistant version 2021.11.5.

All devices are connected to the cloud. So I use the HTTP protocol to communicate with the devices for Home Assistant. The problem *only* appears on the mss210 devices. I also have a MQTT Broker running, but it's not used for the integration so the Meross Hub integration is deactivated.

## Version of the custom_component
- "version": "2.3.3"

## Hardware and firmware versions of the effected devices
- Firmware: 2.2.2
- Hardware: 2.0.0

## Home Assistant version
- Home Assistant OS 6.6
- supervisor-2021.10.8
- core-2021.11.5

## Describe the bug
During regular operations in Home Assistant (eg. showing a dashboard) the entities of the mss210 become unavailable. In that state  its not possible to control them or even fetch data, like on/off, from them. The problem appears randomly so the devices become available and unavailable several times a day for a different amount of time. The problem is not global, so not all devices become unavailable at the same time, it's totally random. Sometimes plug A sometimes plug B, sometimes both, sometime plugs A&F, etc. 

Further all devices have a fixed ip address and during the outage of the entities, the devices can still be controlled with the Meross App on my phone. 

## Things I tried
After reading through the open and closes issues, I tried the following things:
- check the connectivity: ✅ done, all devices have a proper connection with at least 50% of WIFI power
- connect the devices with your meross credentials: ✅ done, all devices were added using my personal meross credentials to fetch the device id
- tweak the integration setting: ✅ done, I set the protocol to "http" and even played with the polling period, it's set to 10 at the moment
- check the debug logs: ✅ done, the file is attached to the issue

## What I understand from the logs
In the log you can see a clear error for the client connection. So there is some problem which causes a disconnect, sadly I'm not a python developer, so I'm not able to fix this my self but I'm very interested in the root cause of the problem and how to fix it.

## Debug log
[mss210-1637740440.csv](https://github.com/krahabb/meross_lan/files/7594362/mss210-1637740440.csv)

## Last thoughts
First of all thank you for the integration💙! Besides my problem it's working really great and I'm super thankful that you take care of the integration development and maintaining. So if you need any further information that's useful to fix these issue, feel free to ping me! I'll try all I can to help you solving this problem.

Cheers Patrick

**Comment by krahabb** [comment]
Hello @patrick-blom!
Thank you for your 'Thoughts' :)
Beside still fighting with some random http disconnects/timeouts which I still don't understand I suspect your issue, being so frequent by the trace, lies in an incorrect device key (just a guess and a check away).
If you left the 'key' field empty in meross_lan, my code is likely using an hack to communciate with the device and this could lead to communication issues.
If this is the case please follow [this](https://github.com/krahabb/meross_lan/issues/92#issuecomment-929545495). You'll have to remove the integration and reconfigure it from scratch since the config flow is still missing the ability to overcome this once configured the first time

At any rate, I've just published (pre-release right now) a new version with some 'tweaks' in order to be more robust against http disconnections. Still, they're just tricks and are expected to work only when the issue is really random and not too frequent, else these tweaks might just add more instability.

Let's see!

**Comment by patrick-blom** [comment]
Hey @krahabb,
thx for replying so quick!

I will remove the devices which have problems and try to add them back again with focus on the device key. If this will not solve the problem, I'll try the pre-release version of the integration. I'll keep you up2date.

Thx for taking care and stay safe!

Cheers Patrick

**Comment by patrick-blom** [comment]
Hey @krahabb 
I just recognized something strange and I guess that's the root cause of my problem. I checked all integrations again, and I realized that all devices which are working, have no device key in the configuration form. All mss210, which don't work, have one. ***But*** it's all the ***same*** key oO 

I removed two integrations and added them back again and I got the *same* key for both after I logging in with my credentials during the integration setup. Is that the correct behavior? I don't think so :D because why should all devices use the same key?

Is there maybe a caching problem with forms content or a result cache for http responses?

Cheers Patrick

**Comment by krahabb** [comment]
I see your point but this is how 'official' Meross setup works: you have just 1 unique key per account which is used on all of the devices associated with that, even though every device could theoretically have its own.

your devices with empty key, if still paired with Meross, are working with the 'key hack' algorithm.
The ones with non empty key are working with that key i.e. they'll work good if the key is right else they don't work

**Comment by patrick-blom** [comment]
Ok, got it! Thx for clarification! So that's not the root cause of the problem, damn ^^ 

Do I have to reconfigure all devices/integrations if I'll switch to the 2.4.0beta version you mentioned or can I just update the component?

**Comment by krahabb** [comment]
No need to reconfigure: just install and restart :)

**Comment by patrick-blom** [comment]
@krahabb I tested the beta version for about 12h now and had yet no problems with unavailable entities. So for me it seems to solves the problem! I will test it more during the weekend, if no problems occur the issue can be closed from my side 🤓

I guess the 3 times loop you built around the async http call in the meross_device.py did the trick for me. Maybe you should make the sleep interval configurable, 100ms seems to work well but I don't know how easy it is to get banned by the meross api, especially if you're repeating calls so quick ^^ 

Never the less thx a lot 👏

Cheers Patrick

**Comment by krahabb** [comment]
Ahh..don't worry about api-ban or so..the http calls are all local to the device so no cloud intermediation whatsoever. There could be an issue if the device firmware itself stalls or crash when you query it back to back but I've never find an issue directly related to  commands in rapid succession so I'm quite confident that minimal delay wuold not disrupt the device behaviour

**Comment by patrick-blom** [comment]
@krahabb after one weekend of testing, the problem is solved with the upcoming version. 

Thx & take care 🤓
