### ISSUE TITLE
ERROR IN CONFIGURATION OF MEROSS DEVICES

### ISSUE THREAD

**Issue by Pippodomotic** [krahabb/meross_lan#123]
Hello
First of all I would like to congratulate you on this Home Assistant integration. I recently started using Home Assistant for my home automation because I only used Domoticz. I use Home Assistant Core 2021.9.7 on Synology with DSM 7.0.
So I apologize if my question turns out to be trivial.
I have installed your Custom_Component following all the procedures reported. I can see my Meross sockets on the Home assistant panel but I can't use them because the configuration produces these errors:
“This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components / meross_lan / switch.py: 8
Integration: Meross LAN (documentation, issues)
First occurred: December 1, 2021, 10:32:25 pm (3 occurrences)
Last logged: 1 December 2021, 22:32:34

Error setting up entry mss425f 1908159447162439088848e1e950fe06 for meross_lan
Error setting up entry mss310r 1907034581699339085648e1e95045be for meross_lan
Error setting up entry mss310 1806224340827325133134298f134bd4 for meross_lan
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry (hass, self) # type: ignore
  File "/volume1/@appdata/homeassistant/config/custom_components/meross_lan/__init__.py", line 91, in async_setup_entry
    device = api.build_device (device_id, entry)
  File "/volume1/@appdata/homeassistant/config/custom_components/meross_lan/__init__.py", line 326, in build_device
    from .meross_device_switch import MerossDeviceSwitch
  File "/volume1/@appdata/homeassistant/config/custom_components/meross_lan/meross_device_switch.py", line 17, in <module>
    from .switch import MerossLanSwitch
  File "/volume1/@appdata/homeassistant/config/custom_components/meross_lan/switch.py", line 8, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'ENTITY_CATEGORY_CONFIG' from 'homeassistant.const' (/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/const.py) ".

I might ask what to do in order to properly configure my Meross sockets. I hope your support can be of help to others as well.

Thanks.

**Comment by krahabb** [comment]
Hello @Pippodomotic ,
yes this was a bug due to my lack of testing on older releases :(
The last release 2.4.2 (Rush.1) fixes these compatibility issues

**Comment by Pippodomotic** [comment]
Bravissimo krahabb, your suggestion worked perfectly. Now I see all three of my Meross smart electrical sockets and I can also see all the data of energy consumption, voltage etc.
Perfect Home Assistant Component! Now I am able to automate Meross devices that I was unable to automate with Domoticz.
I send you my compliments.

**Comment by krahabb** [comment]
Thank you :)
