### ISSUE TITLE
Cannot remove integration and it's dependencies from HA

### ISSUE THREAD

**Issue by unlucio** [krahabb/meross_lan#141]
## Version of the custom_component
v2.4.3
-->

## Configuration

```yaml
I'm not using any yaml configuration, I just installed the integration via hacs and added it to my system through the web interface and the "add integration" button
```

## Describe the bug
There is no clear way on how to remove this integration from HA as it misses the `...` menu.
Removing the package from the `homeassistant/custom_components` directory (or removing it through` hacs`) leaves stuff around in a way it makes it apparently impossible to "reset" it.

<img width="268" alt="Screenshot 2021-12-20 at 23 09 01" src="https://user-images.githubusercontent.com/778799/147074211-3c7d1854-dd0f-4509-bff6-fe6a0748b116.png">

For some reason, all my meros plugs went unresponsive kind of out of the blue.
<img width="1336" alt="Screenshot 2021-12-20 at 23 09 27" src="https://user-images.githubusercontent.com/778799/147074662-3b117d4c-15ba-44ca-9ec8-b0cf71a3b16d.png">
In a couple of days I both updated HA to `2021.12.3` as well as revamped my lan+dhcp config, which very likely changed IPS for all my meros plugs. None of them has a reservation in my dhcp so it's hard to tell.
Never the less it took me a couple of days to realize all of them went unresponsive (one of them takes care of turning on an extra heater in my bathroom to warm it up for my morning shower. I had to shower in the cold to realize something was wrong), so not really sure which change did it.
All my plugs show up and work perfectly fine in the meros app on my iPhone
It didn't seem like a big issue: I'll just remove the integration, HA will forget about them, add the integration back and it'll detect the plugs again. King of the traditional "fix the unresponsive device" dace I'm sure many went through with many integrations over the years. Or so I thought.
Going into the Integration page I found myself staring at the meros integration lacking any apparent way to remove it. Fine, I'll delete the module, reboot HA, and install it again. Seemed yet again enough to have those plugs been rediscovered.
I turned about to be wrong again: as soon as I add the module back all the stale devices show up again as nothing happened, and I'm back to square one.
Now, besides my showering in the cold problems, there should really be a clear and clean way to just remove this integration and all its dependencies from the system. Wouldn't you agree?

## Debug log
```text
there are no real logs possible for this kind of issue
```

**Comment by unlucio** [comment]
Sorry turns out there is, it's just confusing and it's due to HA. Nothing this module can do. My bad.

**Comment by krahabb** [comment]
Ah ok, just read this after commenting the same issue in another thread ;)

**Comment by davidahmed** [comment]
@unlucio and how did you finally remove these devices?
