### ISSUE TITLE
MSS310x stop working after fw update to 2.1.2

### ISSUE THREAD

**Issue by Cippo2019** [krahabb/meross_lan#158]
Hello
after update to 2.1.2 for MSS310X the device stop working :-(
below some info

Meross Lan 2.4.3
HA Hassos 2021.12.10
OS 7.1
Supervisor 2021.12.2

i have aslo this warning in logger
022-01-20 20:13:33 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(2010199978996951803248e1e93618d2) error in async_http_request: {'error': {'code': 5001, 'detail': 'sign error'}}

could you help me ?
wbr
Tiziano

**Comment by Cippo2019** [comment]
Hi Krahabb, 
sorry in advance for that question, but just to understand , do you think that may be you will be able to solve the problem regarding lan comunication with meross devices (with upadated firmware) and you rmodule ?

I ask it because I saw some other posts regarding this and maybe I have to consider to change devices... :-(

or, do you know if it is posssible to downgrade the meross firmware ( I tried to search on meross site without success)

thk

Tiziano

**Comment by Cippo2019** [comment]
solved following this procedure https://github.com/krahabb/meross_lan/issues/148

**Comment by krahabb** [comment]
Hello @Cippo2019 and sorry for my 'vacancy'...
I guess the latest firmwares are all closing down on the security hole which allowed meross_lan to communicate without knowing the secret key.
Glad you found the way to fix it!

**Comment by Cippo2019** [comment]
Hellp @krahabb  
thanks for answer
Yes for now I have solved but what about the future and new firmware ? 
this is a open question for all of us that at the moment are using your amazing addon

what do you think abiut future ?
will you investigate on new firmware or the only option is to avoid fw upgrade ? 

wbr

Tiziano

**Comment by krahabb** [comment]
Hello @Cippo2019 ,
The issue itself lies in the ability, for meross_lan, to try use the device even with an empty key.
This used to work with a little trick but as we see, newer firmwares are more robust so you just need to enter the correct key in meross_lan and everything starts working again.
I should just 'refine' the UI and/or some warnings to clearly state that, in order to avoid issues, it's always better to set the proper key :)
