### ISSUE TITLE
Meross 310x with 2.1.2 Firmware (after update) doesn't work

### ISSUE THREAD

**Issue by matfil92** [krahabb/meross_lan#164]
Hi,
This morning, I updated my socket MS310x, and they updated to the last firmware 2.1.2 version. 
After the update, the socket is no anymore manageable from Home Assistant. All the MSS310 devices show as unavailable; I've also the MSS310 (without X in the model name), which works correctly.

Any update on the HACS Meross LAN component that allows us to use the 2.1.2 firmware version?

**Comment by leofabri** [comment]
Same problem! I hope they didn't mess up with the possibility of controlling the device

**Comment by krahabb** [comment]
Hello @matfil92 and @leofabri ,
I don't know what this new firmware brings in but in most of this kind of issues everything was related to a wrong (possibly empty) key set in meross_lan. This used to work but is increasingly becoming an issue with recent firmwares updates.
When setting a correct device key in meross_lan everything works again. The key need to be retrieved from the meross cloud account and sadly enough (I'm working on this for the next release) you can't recover the key from the cloud account after the device is initially configured so you're left with dropping and reinstalling the device configuration in integrations. 
If this is not the case and the device doesn't work even with the correct key then it might be that 'Houston we have a problem...'
You could then try catching a trace from the device integration configuration and post it so I could better inspect what's the issue

**Comment by matfil92** [comment]
Hi @krahabb,
I confirm that removing and add again it works! Probably have lose the UIID
