### ISSUE TITLE
error in async_http_request: 'channel' when upgrading to 2.5.4

### ISSUE THREAD

**Issue by dragonjon** [krahabb/meross_lan#172]
Hi @krahabb  first of all thanks for your work.

## Version of the custom_component
2.5.4

## Configuration
Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

## Describe the bug
previously had version 2.4.3
everything worked fine 4 ms210 and 1 ms310
When upgrading to version 2.5.4 all devices are not available.
I have 2 installations one in production and another in dev in a virtual machine.
the production installation has MQTT installed on the dev installation it is not installed.
The same thing has happened in both installations when updating the version, the Meross devices are no longer accessible
[meross_lan-4b876b1a204fa355055f65619a34b46e-Smart Switch (1806221438054525132934298f11f42f)-5cf9ecdb33931fd2eb50b374f3623cce.json.txt](https://github.com/krahabb/meross_lan/files/8109156/meross_lan-4b876b1a204fa355055f65619a34b46e-Smart.Switch.1806221438054525132934298f11f42f.-5cf9ecdb33931fd2eb50b374f3623cce.json.txt)

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:25
Integration: Meross LAN ([documentation](https://github.com/krahabb/meross_lan), [issues](https://github.com/krahabb/meross_lan/issues))
First occurred: 13:15:31 (5 occurrences)
Last logged: 13:15:31

MerossDevice(1806227523723725132934298f11f45e) error in async_http_request: 'channel'
MerossDevice(1806226324713225132934298f11eae1) error in async_http_request: 'channel'
MerossDevice(1806225280218025132934298f11f402) error in async_http_request: 'channel'
MerossDevice(1806221438054525132934298f11f42f) error in async_http_request: 'channel'
MerossDevice(1806223725357925133134298f135d14) error in async_http_request: 'channel'

**Comment by krahabb** [comment]
Aww..I'm very sorry for that..I left an 'unchecked' access to the channel property which older firmwares clearly don't have...
previous versions were more lenient on this 'missed' field and were able to silently adapt
I'll try to fix it in a reasonable way and re-publish

**Comment by dragonjon** [comment]
Thank you for the prompt response and for your work. It is not an urgent thing since at the moment I can control everything with the meross app. I will wait for you to have time to solve it and as you say to see if there is any more error.

Grazie mille e se hai Bizum potrei offrirti da bere

Sorry for my english an italian

**Comment by dragonjon** [comment]
Hi @krahabb I test the new code and al is working again.

Good work
Thanks
