### ISSUE TITLE
cloud retrieve mode suggests I switch to hack mode

### ISSUE THREAD

**Issue by twhittock** [krahabb/meross_lan#176]
## Configuration

```
```

## Describe the bug
When I attempt to reconfigure mss420f 3.0.0, Firmware: 3.1.1 I cannot get hack mode to work. So I switched to cloud retrieve, but when I then click submit, instead of being given an opportunity to enter my meross cloud credentials, I am given the error "Key error: select 'Hack mode' to allow empty key." Hack mode does not work, it returns the error "Key error: select 'Cloud retrieve' to get from Meross account."

## Debug log

It's unclear what logger settings I need to enable in order to provide information. This is all that is logged currently, probably unrelated to the UI error I'm reporting, more a symptom of the problem I'm trying to fix by switching to cloud retrieve mode.

```text

yaml

This error originated from a custom integration.

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:25
Integration: Meross LAN (documentation, issues)
First occurred: 11:57:00 (4 occurrences)
Last logged: 11:57:00

MerossDevice(2006280724788490817148e1e9216663) error in async_http_request: {'error': {'code': 5001, 'detail': 'sign error'}}
MerossDevice(1912033761949090805948e1e91259a0) error in async_http_request: {'error': {'code': 5001, 'detail': 'sign error'}}
MerossDevice(1912039687493890805948e1e9125b64) error in async_http_request: {'error': {'code': 5001, 'detail': 'sign error'}}
MerossDevice(1806223616531725133234298f135ebb) error in async_http_request: 'channel'

```

**Comment by krahabb** [comment]
Yes, I've rechecked the flow and there's an 'hole'.
You could just insert a 'whatever not-null' key to be delivered to the cloud retrieval form.
I'm fixing for the next release

**Comment by twhittock** [comment]
Thanks - the workaround worked for me, and the new release seems to work, too! Thank you so much!
