### ISSUE TITLE
Devices Lost on Router Reboot

### ISSUE THREAD

**Issue by hampelo** [krahabb/meross_lan#178]
Version 2.2.5
-->

## Configuration

HA 2.2.9

```

## Describe the bug
Rebooting my router has permanently lost several of my devices.  It is possible that they have changed IP.  They are not being rediscovered.  Is it possible to repair this?  Do I have to delete and read the integration?

The devices all still work with the Mross app.




```

**Comment by krahabb** [comment]
Hello @hampelo ,
With the latest release (2.5.4) you can edit the ip configuration for the device so you can update the entries without reconfiguring them from scratch. 
In version 2.2.5 this is not possible and you're left with remove-readd the configuration entry
