### ISSUE TITLE
Meross 2.5.7  MSS310 Energy

### ISSUE THREAD

**Issue by JartX** [krahabb/meross_lan#181]
Meross dont reset the last day energy value from March

11 devices  Mss310 2.0.0

Meross Lan 2.5.7

Core 2022.3.1

![Screenshot_20220306-024106_Quickstep](https://user-images.githubusercontent.com/8399211/156905644-1e330d13-a0cc-4519-8ada-3e386cbb2991.png)
![Screenshot_20220306-023937_Quickstep](https://user-images.githubusercontent.com/8399211/156905645-e63f3123-f7d4-427c-b370-5a8e20311be8.png)

Manu thanks for your time!!!!

**Comment by krahabb** [comment]
Hello @JartX ,
That's likely not related to 2.5.7. Do you have any previous history to see what happened in the last 10-15 days?
Also, are your mss310 binded over MQTT or do they still operate with the meross app?
The issue anyway could be related to an improper timestamp setting on the device. If they talk to your own MQTT broker, meross_lan tries to configure the exact time setting for the plug (but that couldnt work too...). If instead they're still connected to the internet and able to reach any external NTP server they should be able to get a proper time setting...anyway you should see a warning in HA log stating the device timestamp is 'incorrect' (this is logged once in a while but you should definitely find it)

**Comment by enricoso** [comment]
I have the same issues. my ms310 operate under http (no Mqtt). 
Maybe could be a cloud issue?

![image](https://user-images.githubusercontent.com/66533376/156920359-5173175d-451c-4ca7-a931-e39cbb40028c.png)

Power consumption today reports 2,98 Kwh now although my washing machine is off now for two days.

**Comment by krahabb** [comment]
Wow..this adds up to the mess... ;)
By the look of it the device timestamp is correct..but still it reports a 'wrong' energy reading.
Where do this screenshot comes from? is it the official meross app ? (I don't have an iPhone so I'm just guessing). If not, I guess this is a screenshot from homekit, maybe the meross app reports a different value?

**Comment by enricoso** [comment]
This screenshot is from iphone meross app

**Comment by JartX** [comment]
> Hello @JartX , That's likely not related to 2.5.7. Do you have any previous history to see what happened in the last 10-15 days? Also, are your mss310 binded over MQTT or do they still operate with the meross app? The issue anyway could be related to an improper timestamp setting on the device. If they talk to your own MQTT broker, meross_lan tries to configure the exact time setting for the plug (but that couldnt work too...). If instead they're still connected to the internet and able to reach any external NTP server they should be able to get a proper time setting...anyway you should see a warning in HA log stating the device timestamp is 'incorrect' (this is logged once in a while but you should definitely find it)

Hi! Mqtt mode

Last 15 days the 11 devices has worked fine, the problems started at 1 of March at 01:00

**Comment by krahabb** [comment]
Hello @JartX ,
It looks like the plug is really reporting these values though. This is the paylod it is sending us:
```

          "consumptionx": [
            {
              "date": "2022-03-01",
              "time": 1646179080,
              "value": 11156
            },
            {
              "date": "2022-03-02",
              "time": 1646265480,
              "value": 11726
            },
            {
              "date": "2022-03-03",
              "time": 1646351880,
              "value": 7083
            },
            {
              "date": "2022-03-04",
              "time": 1646438282,
              "value": 9974
            },
            {
              "date": "2022-03-05",
              "time": 1646524688,
              "value": 6924
            },
            {
              "date": "2022-03-06",
              "time": 1646567399,
              "value": 5364
            },
...
```
For each day you can see the accumulated Wh and the time of the last sample (roughly before midnight). So it really looks like the plug itself is behaving 'widly'. My plugs (also on MQTT and meross_lan 2.5.7) are correctly resetting to 0 in the meantime but they're on firmware 2.1.4 so maybe that's a bug in your firmware version. It would be nice to see if the @enricoso plug is on the same firmware as yours since it looks he's experiencing the same behaviour even though its plug is paired to the meross cloud (this would again strongly suggests the issue lies in firmware)

**Comment by krahabb** [comment]
Quick 'old style' suggestion:
have you tried power-cycling the plug? if it's an internal state bug it could be reset so...

**Comment by JartX** [comment]
> Sugerencia rápida de "estilo antiguo": ¿ha intentado apagar y encender el enchufe? si se trata de un error de estado interno, podría reiniciarse, así que ...

yes , haha replugged at not work fine, always takes using yesteday values, for example: 6 March finally at: 5000wh but started at 2500wh, then today start at 2500kwh, it always report the last real consumption, is so very strange.
![Captura de pantalla de 2022-03-07 10-23-54](https://user-images.githubusercontent.com/8399211/157003450-4bc14854-c25e-4e59-baf1-2564b69337a5.png)

Everything started without further ado on March 1st, and nothing was updated, it had been working fine since November of last year, without failing a single day.

**Comment by JartX** [comment]
Any way to remove all values like on shelly?
![Shellies](https://user-images.githubusercontent.com/8399211/157006153-54314aa5-c2f8-4f81-b428-7146c2019487.png)

**Comment by JartX** [comment]
![mqtt](https://user-images.githubusercontent.com/8399211/157012082-20a64c01-b3e1-401a-9947-d332c01ee7e1.png)
Check it, please, can set to 0 all values of consumptionX? Can you say me like can do it? many thanks!

**Comment by krahabb** [comment]
I hardly believe it would be possible but I could experiment a bit.
The fact is that even if I reset the values in the plugs, homeassistant already stored the history in 'recorder' so it would be no use.
meross_lan only saves the last (current day) value on every polling cicle.
As for the 'power-cycling' that would not reset the plug memory, nor the HA history too, but could make the plug start to reset correctly every midnight so, if it works, you should see the plug restarting from 0 from the day after the reset.

**Comment by JartX** [comment]
Check that point:   "2022/03/07 - 12:33:33",
        "RX",
        "mqtt",
        "GETACK",
        "Appliance.Control.ConsumptionX",
        {
          "consumptionx": [
            {
              "date": "2022-03-01",
              "time": 1646179080,
              "value": 11156
            },
            {
              "date": "2022-03-02",
              "time": 1646265480,
              "value": 11726
            },
            {
              "date": "2022-03-03",
              "time": 1646351880,
              "value": 7083
            },
            {
              "date": "2022-03-04",
              "time": 1646438282,
              "value": 9974
            },
            {
              "date": "2022-03-05",
              "time": 1646524688,
              "value": 6924
            },
            {
              "date": "2022-03-06",
              "time": 1646607486,
              "value": 6216
            },
            {
              "date": "2022-03-07",
              "time": 1646652810,
              "value": 8122
            },
            {
              "date": "2022-02-08",
              "time": 1644364683,
              "value": 3235
            },
            {
              "date": "2022-02-09",
              "time": 1644451081,
              "value": 4609
            },
            {
              "date": "2022-02-10",
              "time": 1644537480,
              "value": 6425
            },
            {
              "date": "2022-02-11",
              "time": 1644623880,
              "value": 3964
            },
            {
              "date": "2022-02-12",
              "time": 1644710289,
              "value": 7694
            },
            {
              "date": "2022-02-13",
              "time": 1644796680,
              "value": 3772
            },
            {
              "date": "2022-02-14",
              "time": 1644883089,
              "value": 3939
            },
            {
              "date": "2022-02-15",
              "time": 1644969488,
              "value": 4715
            },
            {
              "date": "2022-02-16",
              "time": 1645055885,
              "value": 4271
            },
            {
              "date": "2022-02-17",
              "time": 1645142284,
              "value": 4998
            },
            {
              "date": "2022-02-18",
              "time": 1645228684,
              "value": 3732
            },
            {
              "date": "2022-02-19",
              "time": 1645315082,
              "value": 6503
            },
            {
              "date": "2022-02-20",
              "time": 1645401483,
              "value": 4021
            },
            {
              "date": "2022-02-21",
              "time": 1645487881,
              "value": 4311
            },
            {
              "date": "2022-02-22",
              "time": 1645574288,
              "value": 4125
            },
            {
              "date": "2022-02-23",
              "time": 1645660685,
              "value": 3871
            },
            {
              "date": "2022-02-24",
              "time": 1645747085,
              "value": 4222
            },
            {
              "date": "2022-02-25",
              "time": 1645833484,
              "value": 3579
            },
            {
              "date": "2022-02-26",
              "time": 1645919884,
              "value": 5630
            },
            {
              "date": "2022-02-27",
              "time": 1646006284,
              "value": 3954
            },
            {
              "date": "2022-02-28",
              "time": 1646092681,
              "value": 4146
            }
          ]
        }
      ],
      [

Any way to reset them or remove all data at 00:00?

**Comment by JartX** [comment]
You can verify that in February all the consumptions were correct, but in March from day 1, the consumptions of the previous day began to be added, could all the consumptions be emptied at midnight? or before midnight? I'm lost sorry

**Comment by enricoso** [comment]
My plug firmware version is 6.1.10.

**Comment by sanglt** [comment]
I'm having the same issue. The value of property energy is not reset. I started to use this addons about 5 days ago and try to setup Energy monitoring but don't understand what is the value of this. Searching around and I saw this issue which is the same thing happen to me.

This is the value of energy from addons:
<img width="1662" alt="Screen Shot 2022-03-08 at 1 01 56 pm" src="https://user-images.githubusercontent.com/128535/157158103-419486dc-6790-45f9-ae96-dbbb60f823c3.png">
This is the value report from iOS app:
![image](https://user-images.githubusercontent.com/128535/157158176-ef6c1bd8-290d-4a3d-94c6-d1fbc295b87c.png)

**Comment by enricoso** [comment]
![image](https://user-images.githubusercontent.com/66533376/157384427-0c783b01-8114-4c32-a1ee-8eb1a44f1421.jpeg)

**Comment by enricoso** [comment]
Please check this screenshot. No use of the appliance. No sense at all... The problem is in the firmware or cloud for sure.

**Comment by krahabb** [comment]
I'm strongly convinced too the issue lies in firmware somehow since the ConsumptionX values which we see in the payloads are only managed by the plug itself and I have no option to externally set or change those: meross_lan just read the last value and send it to HA for recording.
The fact that the ConsumptionX payload values 'align' with HA history recording states that meross_lan is not 'bugging' it (which could happen of course if meross_lan was bugged)
From what I understand the ConsumptionX values themselves are 'wrongly' higher than they should so the conclusion the error is in firmware.

> Please check this screenshot. No use of the appliance. No sense at all... The problem is in the firmware or cloud for sure.

From what I see here, it looks like the plug started reporting correctly (0) again from march 7th with a strange step-up on 8th

**Comment by Dizzyikea** [comment]
Hi

I am also having this issue but i think i have a setup that will either shed some light on the subject or confuse more.

I have three devices

mss310 2.0.0 Firmware: 2.1.14 This one is working fine and resetting each day as it should
mss310 2.0.0 Firmware: 2.1.15 This one only did not reset for the 1st time yesterday (8th march)
mss310 2.0.0 Firmware: 2.1.15 This one has not been resetting since the 1st March like many others

My devices are not connected to cloud or MQTT, i originally got them talking to Hassio via MQTT and they got there IP address fine this was many months ago. Since that connection the SD Card in the pi i had the MQQT server running on went bad and i turned it off the mss310 just carried on working so i never set MQTT back up and disconnected the pi, so now i assume they are just local IP controlled? Which unless i'm wrong leaves us more confused as two devices on the same firmware started doing it different days (also the .14 is still working though) and it's not MQTT or cloud as i use neither.

**Comment by javferper** [comment]
Hello, I have the same problem for 3 days just coinciding with the HA update core_2022.2.9.
In case it adds some light.
Greetings and thanks

**Comment by coolweb** [comment]
I contacted Meross support and I received a reply:
Thank you for contacting Meross.
Sorry for the trouble caused for you. For some of MSS310 smart plug, the power consumption data has a problem in showing correct data and we are working on fixing this issue.

Apologize again for any inconvenience caused on this issue.

Thank you for your concerning!

**Comment by JartX** [comment]
> I contacted Meross support and I received a reply: Thank you for contacting Meross. Sorry for the trouble caused for you. For some of MSS310 smart plug, the power consumption data has a problem in showing correct data and we are working on fixing this issue.
> 
> Apologize again for any inconvenience caused on this issue.
> 
> Thank you for your concerning!

Yep, can confirm that it is problem of firmware, Meross Lan has not problem in that point, but think that can change the sensor of energy to integrated integration, now home assistant count the energy

**Comment by Daibutt** [comment]
Just for info, all my MSS310's are at firmware 2.16 and these have had the same problem since March 1st. 
Let's hope they can roll out a 2.17 with a fix :)

**Comment by tjstamp84** [comment]
I've raised a support case too via their email support portal https://www.meross.com/support/Email_Support 

hopefully this gets fixed soon as it's trashing my energy dashboard completely at the moment. 

![image](https://user-images.githubusercontent.com/102150246/159462344-a8537b49-053f-4939-bc85-ffa578788e1f.png)

**Comment by tjstamp84** [comment]
**Update: Meross have replied suggesting a reset to clear the error. will test it on one of my plugs and report back.**



_> The device functions are normal, this is a bug from the power use data reading, please reset the MSS310 to clear the wrong power use data, "remove" the device in device settings or you can press the power button 5 seconds to reset, then reconnect the MSS310 to Meross app.
> 
> The device settings and history power use data will be cleared after the reset, sorry for the inconvenience cuased and we have informed this issue to our R&D department, we will avoid the problem to happen again. Thanks a lot for your understanding._

**Comment by Daibutt** [comment]
Just noticed that all my MSS310's reset to zero at midnight last night, and are now reading corrcetly. 
F/W still at 2.1.16. 
How bizarre !?

**Comment by tjstamp84** [comment]
I was about to say that the hard reset process works, but it looks like they have resolved the problem. The 5 plugs I removed from the app and did the reset on have been good for a few days, the rest of the plugs that I didn't reset, suddenly started reporting correct figures again yesterday.
