### ISSUE TITLE
Downgrading? Installed 2.5.7 Just got notification for v2.5.4

### ISSUE THREAD

**Issue by Joshndroid** [krahabb/meross_lan#184]
HA is HASS plugin is advising a new available update which is listed as 2.5.4 is this correct?

![image](https://user-images.githubusercontent.com/5584652/161648900-ba64a7dc-04e1-4a02-a89a-f9bd48e0f2a8.png)

**Comment by figorr** [comment]
Unfortunately I downgraded yesterday to v2.5.4 and now HACS it is not seeing the v2.5.7 as available again. So I am still in v2.5.4.
It is curious because HACS updated some other custom_components this morning but it is recognizing Meross Lan v2.5.7 as an available update.

**Comment by Joshndroid** [comment]
> Unfortunately I downgraded yesterday to v2.5.4 and now HACS it is not seeing the v2.5.7 as available again. So I am still in v2.5.4.
> 
> It is curious because HACS updated some other custom_components this morning but it is not recognizing Meross Lan v2.5.7 as an available update.

Oh no... i typically just update and away I go.... i thought the numbers were odd which kinda saved me on this occasion

**Comment by krahabb** [comment]
Well..looks like the 2.5.7 release is 'gone' from github...though I didn't touch anything so it's either a glitch in github or someone hacked me..I'm investigating

**Comment by nao-pon** [comment]
@krahabb Pre-release and unreleased tags now seem to be ignored.

- https://github.com/krahabb/meross_lan/releases
- https://github.com/krahabb/meross_lan/tags

**Comment by figorr** [comment]
Thank you. It is solved.  The 2.5.7 update appeared again.

**Comment by krahabb** [comment]
I'm sorry for the issue.
Contacted GitHub and turned out that my versioning scheme is not so well compliant with Semantic Versioning so I guess some automated software check hid or 'demoted' the actual version.
I'm going to fix this going on but I'm scared the actual/past tagging scheme would pollute the version checking algorithms forever :(
We'll see goin on...

**Comment by Joshndroid** [comment]
Good to hear you have worked out the root cause. I also worry that it may poison the future however apart from renaming the whole thing i don't know if you have any other option??
