### ISSUE TITLE
Unable to connect to Meross account

### ISSUE THREAD

**Issue by ayoward** [krahabb/meross_lan#186]
Hello,

I have recently installed Home Assistant so am fairly new to this, but I like to think I am IT literate (I have managed to make a career out of it) however, I am struggling with getting Home Assistant/Meross LAN to connect to my account for the device key.  

I bought a Meross Smart WiFi Surge Protector specifically because of the Home Assistant integration and while I have successfully attached it to the WiFi, set up a Meross account on the app and linked the device, installed Meross LAN via HACS, but when it comes to the configuration, which rightly or wrongly I set as Cloud Retrieval (not sure how to change that now, but that's another issue) it is asking for my credentials for Device Key Retrieval which when I put them in, it fails every time.  

Does anyone know what I am doing wrong?  I know the credentials are correct as I have them stored in my password vault.

Any help would be greatly appreciated.

Thanks,

Andrew

<img width="208" alt="Meross" src="https://user-images.githubusercontent.com/103206712/162281176-923b4d1b-9d0e-434e-b0b6-ba386e046330.png">

**Comment by krahabb** [comment]
Hello @ayoward ,
I see by the screenshot you get an 'unable to connect' error so I would investigate why you can't reach to the meross login servers which (as implemented in meross_lan) should respond on 'https://iot.meross.com/v1/Auth/Login'

**Comment by squaredcircle** [comment]
I also have this problem - same error message "unable to connect". My instance of Home Assistant can communicate with https://iot.meross.com/v1/Auth/Login as seen here:

![image](https://user-images.githubusercontent.com/7134818/175764658-267672f7-e7ae-4172-a5ea-41a8e6175387.png)

Anything I can try to make this work?

**Comment by krahabb** [comment]
Hello, I've checked the meross_lan code in search of clues and I have to admit the 'unable to connect' error is raised on any error, I've also seen that now, if you enter wrong credentials, the actual flow implementation just 'works' by returning an empty key with no error warning to the user so I'm going to try refactor the code a bit trying to add more detailed informations on the error.

**Comment by krahabb** [comment]
Hello @squaredcircle,
I've just released an 'alpha' with a small fix so to have better insights on this error. You should see an additional field on the form stating the actual reason for the error so we might have a better chance to further investigate it

**Comment by squaredcircle** [comment]
Hey @krahabb,
I updated to the new alpha and tried again - here's the error:

![image](https://user-images.githubusercontent.com/7134818/175794751-d33c623a-6f71-4a14-a6c2-acdaf2cb6595.png)

**Comment by krahabb** [comment]
Awww..
this message looks like the key field is missing from the server response. The reason is still unclear though since this error happens in an unexpected piece of code. The server response usually carries the reason but we've missed that. 
I'll better refine the error handling so to try have this 'reason' shown in the form

**Comment by krahabb** [comment]
> HI guys, Not sure if this is helpful or not. I had a " character in my original password for meross which broke the api call. Once the password was changed not to contain that character it was fine.

Hello @aaronschriever , that could explain the issue. I'll check if the password encoding needs some extra care when using these characters

**Comment by bossloper** [comment]
I had an ! (exclamation mark) in my password. It failed to log in to the cloud unless I changed my password to not have it.
v2.6.2

**Comment by krahabb** [comment]
Hello @bossloper ,
I'll review the actual implementation to try understand why!
Thank you for sharing this

**Comment by krahabb** [comment]
Hello @cpighin,
I still haven't checked the code for this and I guess the issue lies in some special character not being encoded correctly (like the '!' in the previous post).
Can you share, if any of these specials is used inside your password ? or  just say 'yes there are a ton of them' :)

**Comment by cpighin** [comment]
Hallo krahabb,

thanks for replying ... NO, my Meross password consists only of lowercase and uppercase letters and numbers :(

**Comment by cpighin** [comment]
Well, so I just have to wait for a new version of Meross LAN and try the integration again, counting on the possibility of reporting a more precise error message?
From the information you have, do you think there are many or few users who are unsuccessful with the integration in Home Assistant?

**Comment by krahabb** [comment]
It's hard to say...since I don't have the big picture of how many users are actually using meross_lan. I guess some in the like of 1 every 10 has few issues actively reported

**Comment by cpighin** [comment]
thanks

**Comment by andrelung** [comment]
This was my previous password:
`garlicky-allergen-knowing-jalousie`

changing it to something simpler (and shorter) made the integration work.

**Comment by TheMastro-11** [comment]
Hi, same problem, more specific error:`int([x]) -> integerint(x, base=10) -> integerConvert a number or string to an integer, or return 0 if no argumentsare given.  If x is a number, return x.__int__().  For floating pointnumbers, this truncates towards zero.If x is not a number or if base is given, then x must be a string,bytes, or bytearray instance representing an integer literal in thegiven base.  The literal can be preceded by '+' or '-' and be surroundedby whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.Base 0 means to interpret the base from the string as an integer literal.>>> int('0b100', base=0)4`

**Comment by DrOctogone** [comment]
> Hi, same problem, more specific error:`int([x]) -> integerint(x, base=10) -> integerConvert a number or string to an integer, or return 0 if no argumentsare given. If x is a number, return x.__int__(). For floating pointnumbers, this truncates towards zero.If x is not a number or if base is given, then x must be a string,bytes, or bytearray instance representing an integer literal in thegiven base. The literal can be preceded by '+' or '-' and be surroundedby whitespace. The base defaults to 10. Valid bases are 0 and 2-36.Base 0 means to interpret the base from the string as an integer literal.>>> int('0b100', base=0)4`

Hello, I had the same problem as you. I simply deactivated 2-factor authentication with the application and it worked.

**Comment by tombout** [comment]
Hi, I have a similar problem. I get the error message: 'Expecting value: line 1 column 3022 (char 3021)' when I try to connect a meross-smart-switch.

**Comment by krahabb** [comment]
Hello @tombout,
Issues about the login process (especially the latest from @DrOctogone and @TheMastro-11) were fixed with `Moonlight` release back in February. There was a lot going on there with a 'big' api change from Meross and the added multi-factor authentication but then, it was finally revised and tested to work at the time (now, things keep changing so if something worked before it might not be the case anymore but...)

Now, your error is a bit different and likely a different issue. Which version of meross_lan are you using ? Could you also provide more context as to when and where the message appears? I must suppose you're trying to add a new device to HA...
To better inspect what's going on I suggest you to enable debug logging for the meross_lan integration so that the HA log has more insights abvout the different phases of the configuration process.

**Comment by Jkr1978** [comment]
Hi, 
I am having the  same issue. My HA installation is also quite fresh and I am first getting started. The version of meross lan is v5.2.2
The login to the meross cloud is not working and I get the feedback wrong password although the login is working on the meross app.

**Comment by krahabb** [comment]
Hello @Jkr1978,
Even though 5.2.2 should be 'state of the art' regarding login I suggest you to update to the latest meross_lan (5.3.0) so that we have a solid reference to test with. I've just re-checked it (v5.3.0) and it works fine even with MFA.

**Comment by marwiak** [comment]
I am also having an issue with version 5.3.1. I dont have MFA enabled, i am not an experienced user, so sorry if i make a stupid mistake, but i could not find anything about this on the internet. ConfigEntry.__init__() missing 1 required keyword-only argument: 'discovery_keys'

**Comment by spiralcb** [comment]
Hello, 
I just install meross_lan on my Home Assistant and I have the same issue. 
MFA is not set on my Meross account. 
"ConfigEntry.__init__() missing 1 required keyword-only argument: 'discovery_keys'"

Hope this will be fixed. 

Have a nice day

**Comment by krahabb** [comment]
This new issue (likely a compatibility problem with 2024.10) is being tracked in #497

**Comment by leovj** [comment]
> Hello, I just install meross_lan on my Home Assistant and I have the same issue. MFA is not set on my Meross account. "ConfigEntry.**init**() missing 1 required keyword-only argument: 'discovery_keys'"
> 
> Hope this will be fixed.
> 
> Have a nice day

I have the same problem..

**Comment by krahabb** [comment]
Pls post in #497...this is an old issue not relevant anymore
