### ISSUE TITLE
Would enabling the discussion be possible?

### ISSUE THREAD

**Issue by wsw70** [krahabb/meross_lan#2]
I just discovered your great implementation thank to @Dizzyikea. I built my own some time ago  (https://github.com/wsw70/meross-local-mqtt), it works,  but yours is clearly more refined and integrated.

Would you be willing to enable the GitHub "Discussion" area - I would have a few questions about how you did things (with the idea to contribute if you do not mind), and I would like to avoid making noise in the Issue section.

Thanks for the great work!

**Comment by krahabb** [comment]
Hello!
Sure that's a good idea. I'm a kind of noobie at github so please be patient while I work it out.
I hope to also have some time to better look at your implementation and see if it could be useful to refine and expand mine.
Reading the 'readme' it is inspiring me that I could learn a bit about multi-channel devices (strips) and figure out if they could work on my code ( I tried to make it the more agnostic as possible but couldn't really try it)
The 'Discussion' could definitely be a place to share ideas and tips. Thank you

**Comment by wsw70** [comment]
In order to enable Discussions, head to your project page → Settings

![image](https://user-images.githubusercontent.com/1345886/111870697-81215380-8986-11eb-9cdd-c123c5d62953.png)


Then scroll down

![image](https://user-images.githubusercontent.com/1345886/111870679-60f19480-8986-11eb-95cb-e480d9fc1ecf.png)

You then find the discussion in the main tab of the project (next to Code, Issues, ...)

![image](https://user-images.githubusercontent.com/1345886/111870702-87173480-8986-11eb-8b4b-4f896b646d1e.png)
