### ISSUE TITLE
LAN dhcp discovery not working

### ISSUE THREAD

**Issue by elsharpy** [krahabb/meross_lan#203]
## Version

2.6.1
HA version 2022.7.7
Meross MSS310 and MSS210

## Describe the bug

I have a supervised docker version of HA installed on a RPI4. It works well and did detect my network devices like my Sonos speakers or my NAS so I assume that dhcp discovery is working as expected.
I installed Meross LAN with HACS then rebooted, none of my 4 smartplugs (3 MSS310 1 MSS210) were discovered.
I tried to unplug them several time and did a lot of reboots on my HA installation, still nothing.

On my router I see my smartplugs connected to LAN network, with 192.168.0.XX adresses like my HA server. I am also able to ping them from HA terminal. I checked the logs in debug mode but nothing really helps.
I went through a lot of blogs/youtube videos but devices shows almost instantly after their installation, this is why I am a bit confused.
Am I missing something or is this a potential issue ?
I am new to HA so maybe I'm not doing well. Any help would be greatly appreciated, and I can provide any further information if needed. 

## Debug log

```text

Please tell me which logs I can provide to help :)

```

**Comment by krahabb** [comment]
Hello @elsharpy ,
I guess dhcp discovery over a containerized HA needs special care but I don't really know about the state of the art regarding how the supervised HA works and its environment.
Other integrations could work because they're discovered over different protocols like SSDP or ZEROCONF (the sonos should use that - almost sure)

You can still manually add them, since you actually know their IP. Keep in mind you should 'stick' the same IP to the the same device since meross_lan (even with DHCP working and being routed to HA) is not able to reliably update a changing IP address.

**Comment by elsharpy** [comment]
Thanks for the quick reply.
Well, I tried to manually add the devices but as it wasn't working as well, my first thought was that the issue were related to the ability to "see" or not the devices. In fact I had an error raised when I tried the "Cloud retrieve" method to find the device key (could not log in or something similar).
Finally I tried to change my password and it works, I just replaced special characters that could potentially cause an issue. Working like a charm now :) Thanks !

**Comment by sgelineau17** [comment]
Hello,

I have the same problem but my HA is running on a VM and my smartplug and HA are on different network. The network are carry by my Firewall Fortigate but the flow are opened and the first smartplug we have been discovered but the last one does not want to know anything. 

How how to add the plug manually? I don't see how to do it...

Thanks

**Comment by mschingel** [comment]
I seem the same issue, with the plugs they eventually will auto discover like maybe hours later.  I simply use the method of adding it via the ip address and of course reserve the IP of the device so that it continues to work.
