### ISSUE TITLE
Meross MSS310 failed to connect after FW upgrate to version 6.3.6

### ISSUE THREAD

**Issue by F74** [krahabb/meross_lan#205]
After upgrate two meross MSS310 with the latest version 6.3.6 the device are alway in "not available" state, some times read correctly the value.

I removed and discover again the device but not solve the issue.

The other MSS310 with  Firmware: 2.1.16 work correctly.

I receive a lot of this error on the trace log:

2022/08/12 - 14:17:15   TX      http    GET     Appliance.Control.ConsumptionX  {"consumptionx": []}
2022/08/12 - 14:17:16           auto    LOG     INFO    MerossDevice(2104023535225551806048e1e9699de1) client connection attempt(2) error in async_http_request: Server disconnected
2022/08/12 - 14:17:16           auto    LOG     DEBUG   MerossDevice(2104023535225551806048e1e9699de1) going offline!

see the debug log below

2022/08/12 - 14:17:15           auto    GETACK  Appliance.System.All    {"system": {"hardware": {"type": "mss310", "subType": "un", "version": "6.0.0", "chipType": "rtl8710cf", "uuid": "###########
#####################", "macAddress": "#################"}, "firmware": {"version": "6.3.6", "compileTime": "2022/07/23-10:30:42", "encrypt": 1, "wifiMac": "#################", "innerIp": "########
#####", "server": "##################", "port": "###", "userId": "#####"}, "time": {"timestamp": 1660306631, "timezone": "Europe/Rome", "timeRule": [[1648339200, 7200, 1], [1667084400, 3600, 0]]},
"online": {"status": 1, "bindId": "c7EZenvXRvzsRlIK", "who": 1}}, "digest": {"togglex": [{"channel": 0, "onoff": 1, "lmTime": 1660289975}]}}
2022/08/12 - 14:17:15           auto    GETACK  Appliance.System.Ability        {"Appliance.Config.Key": {}, "Appliance.Config.WifiList": {}, "Appliance.Config.Wifi": {}, "Appliance.Config.WifiX":
{}, "Appliance.Config.Trace": {}, "Appliance.Config.Info": {}, "Appliance.System.All": {}, "Appliance.System.Hardware": {}, "Appliance.System.Firmware": {}, "Appliance.System.Debug": {}, "Appliance
.System.Online": {}, "Appliance.System.Time": {}, "Appliance.System.Clock": {}, "Appliance.System.Ability": {}, "Appliance.System.Runtime": {}, "Appliance.System.Report": {}, "Appliance.System.Posi
tion": {}, "Appliance.System.DNDMode": {}, "Appliance.Control.Multiple": {"maxCmdNum": 2}, "Appliance.Control.Bind": {}, "Appliance.Control.Unbind": {}, "Appliance.Control.Upgrade": {}, "Appliance.
Control.ConsumptionX": {}, "Appliance.Control.Electricity": {}, "Appliance.Control.ConsumptionConfig": {}, "Appliance.Control.ToggleX": {}, "Appliance.Control.TimerX": {"sunOffsetSupport": 1}, "App
liance.Control.TriggerX": {}, "Appliance.Digest.TriggerX": {}, "Appliance.Digest.TimerX": {}}
2022/08/12 - 14:17:15   TX      http    GET     Appliance.Config.Info   {"info": {}}
2022/08/12 - 14:17:15   RX      http    GETACK  Appliance.Config.Info   {"info": {"homekit": {}}}
2022/08/12 - 14:17:15           auto    LOG     DEBUG   MerossDevice(2104023535225551806048e1e9699de1) back online!
2022/08/12 - 14:17:15   TX      http    GET     Appliance.System.All    {"all": {}}
2022/08/12 - 14:17:15   TX      http    GET     Appliance.System.Runtime        {"runtime": {}}
2022/08/12 - 14:17:15   TX      http    GET     Appliance.Control.ConsumptionX  {"consumptionx": []}
2022/08/12 - 14:17:15   TX      http    GET     Appliance.Control.Electricity   {"electricity": {}}
2022/08/12 - 14:17:15   RX      http    GETACK  Appliance.System.All    {"all": {"system": {"hardware": {"type": "mss310", "subType": "un", "version": "6.0.0", "chipType": "rtl8710cf", "uuid": "###
#############################", "macAddress": "#################"}, "firmware": {"version": "6.3.6", "compileTime": "2022/07/23-10:30:42", "encrypt": 1, "wifiMac": "#################", "innerIp": "
#############", "server": "##################", "port": "###", "userId": "#####"}, "time": {"timestamp": 1660306634, "timezone": "Europe/Rome", "timeRule": [[1648339200, 7200, 1], [1667084400, 3600
, 0]]}, "online": {"status": 1, "bindId": "c7EZenvXRvzsRlIK", "who": 1}}, "digest": {"togglex": [{"channel": 0, "onoff": 1, "lmTime": 1660289975}]}}}
2022/08/12 - 14:17:15   TX      http    GET     Appliance.System.DNDMode        {"DNDMode": {}}
2022/08/12 - 14:17:15   RX      http    GETACK  Appliance.System.Runtime        {"runtime": {"signal": 29}}
2022/08/12 - 14:17:15           auto    LOG     INFO    MerossDevice(2104023535225551806048e1e9699de1) client connection attempt(0) error in async_http_request: Server disconnected
2022/08/12 - 14:17:15   RX      http    GETACK  Appliance.System.DNDMode        {"DNDMode": {"mode": 0}}
2022/08/12 - 14:17:15   RX      http    GETACK  Appliance.Control.Electricity   {"electricity": {"channel": 0, "current": 304, "voltage": 2293, "power": 46178, "config": {"voltageRatio": 188, "elec
tricityRatio": 101}}}
2022/08/12 - 14:17:15   TX      http    GET     Appliance.Control.ConsumptionX  {"consumptionx": []}
2022/08/12 - 14:17:15           auto    LOG     INFO    MerossDevice(2104023535225551806048e1e9699de1) client connection attempt(1) error in async_http_request: Server disconnected
2022/08/12 - 14:17:15   TX      http    GET     Appliance.Control.ConsumptionX  {"consumptionx": []}
2022/08/12 - 14:17:16           auto    LOG     INFO    MerossDevice(2104023535225551806048e1e9699de1) client connection attempt(2) error in async_http_request: Server disconnected
2022/08/12 - 14:17:16           auto    LOG     DEBUG   MerossDevice(2104023535225551806048e1e9699de1) going offline!
2022/08/12 - 14:17:17   TX      http    GET     Appliance.System.All    {"all": {}}
2022/08/12 - 14:17:17   RX      http    GETACK  Appliance.System.All    {"all": {"system": {"hardware": {"type": "mss310", "subType": "un", "version": "6.0.0", "chipType": "rtl8710cf", "uuid": "###
#############################", "macAddress": "#################"}, "firmware": {"version": "6.3.6", "compileTime": "2022/07/23-10:30:42", "encrypt": 1, "wifiMac": "#################", "innerIp": "
#############", "server": "##################", "port": "###", "userId": "#####"}, "time": {"timestamp": 1660306636, "timezone": "Europe/Rome", "timeRule": [[1648339200, 7200, 1], [1667084400, 3600
, 0]]}, "online": {"status": 1, "bindId": "c7EZenvXRvzsRlIK", "who": 1}}, "digest": {"togglex": [{"channel": 0, "onoff": 1, "lmTime": 1660289975}]}}}
2022/08/12 - 14:17:17           auto    LOG     DEBUG   MerossDevice(2104023535225551806048e1e9699de1) back online!

**Comment by krahabb** [comment]
Hello @F74 , sorry for the late reply.
It looks like the device is now rejecting the query for power consumption ( you see this request in the log: 'GET Appliance.Control.ConsumptionX {"consumptionx": []}' and then the disconnection).
It is hard to say how to overcome this since I don't have any available MSS310 to test the firmware on at the moment.
In order to at least get the device to work you could disable the energy sensor (power consumption) and see if the connection keeps working this way. We'll need to figure out how to correctly query the device for power consumption anyway but this could allow you to keep using the mss310 at least.

**Comment by F74** [comment]
Hello @krahabb thanks for the reply, Now the Meross Plug work correclty exept for random disconnections (see yellow line in picture).

Probably a router "foult" due to a summer storm, caused the issue, i update the FW during my holliday by remote. 

Wen i came back i restarted the router and the Meross plug, removed the integration and reinstall it and start to work correctly.


![Meross](https://user-images.githubusercontent.com/13820624/185609316-bd16977c-acbd-4944-9bfc-a420642afe42.JPG)

**Comment by krahabb** [comment]
Hello @F74,
thank you for your update... nice to see the fault was not on meross_lan since I was a bit on vacation lately ;)
The random 'disconnects' are something I've always experienced: sometimes the query to the device fails with no apparent reason (at least no reason I can understand) since the query is the same and 99% of the time it works.
