### ISSUE TITLE
MTS 200 unable to setup

### ISSUE THREAD

**Issue by FelixGraf404** [krahabb/meross_lan#220]
Since the last Merossupdate for the MTS 200 I couldn't setup 2 of my 3 thermostat. 

Is it possible to manually discover the both thermostats? The WLAN symbol is blinking an I reset the unit several times. They are not in the ignored section. 

Should I reinstall the whole MerossLAN Integration?

**Comment by krahabb** [comment]
Hello @FelixGraf404 ,
I don't think a full meross_lan reinstall is needed.
One thing could be the device IP address changed so you sould need to manually update the configuration for the device in meross_lan.
I guess your thermostats are also paired to the Meross app: if this is the case, are they working good with the original app?
I don't have any device manual available but the wifi blinking usually means the device is trying (unsuccesfully?) to register to the wifi network or, maybe, it is still in device pairing mode so you need the app to properly (re)configure it.
