### ISSUE TITLE
Update Meross Plug firmeware caused all my plugs to become unavailable in Homeassistant

### ISSUE THREAD

**Issue by mehdic** [krahabb/meross_lan#234]
In Merros application, I was offered a firware update. Once it was done, all my devices became unavailable in home assistant. I am using the latest meross lan, as well the latest homeassistant version.

Help please

**Comment by krahabb** [comment]
Hello @mehdic,
The only (first) thing I could suggest you is to check in the meross_lan configuration entries if the device key is properly set. If you started using meross_lan a while ago, devices were unsecure enough so meross_lan was able to communicate even without a proper key by using an hack. This hole in devices firmware is being closed as many reports from users having your same issue are reporting.
Try to enter the device configuration under 'Integrations' and select the option to retrieve the device key from the cloud. If it works (there are some issues even there!) you chould get the correct key to communicate with yours (the key is the same for all of the devices under the same account so, once retrieved for good you can copy/paste the value in every config entry
