### ISSUE TITLE
Dimming via Alexa not working as expected

### ISSUE THREAD

**Issue by jscmidt** [krahabb/meross_lan#240]
## Version of the custom_component
Newest

## Configuration
I don’t have configured the bulbs via YAML.

## Describe the bug
When A Meross bulb (I've tested MSL100) is off and I turn it on to e.g. 1% brightness via Alexa, that bulb first turns on to 100% and then Fades down to 1%.

## Debug log
Is a debug log relevant here?

**Comment by krahabb** [comment]
Same as #241, I'll check this too :)

**Comment by krahabb** [comment]
Hello @jscmidt,
I can't figure out where the issue lies. Could you please provide e diagnostic trace ran when sending the Alexa command(s) ?

**Comment by jscmidt** [comment]
Do you mean this log or something else? 

[meross_lan-8eeefd12342563a58e2ffea1726fc478-Smart RGB Bulb (21020560309556290d4248e1e94afe07)-a6842b9c651fed70440d34beccb721f2.json (2).txt](https://github.com/krahabb/meross_lan/files/10494350/meross_lan-8eeefd12342563a58e2ffea1726fc478-Smart.RGB.Bulb.21020560309556290d4248e1e94afe07.-a6842b9c651fed70440d34beccb721f2.json.2.txt)

**Comment by jscmidt** [comment]
This now is a MSL120, they have the same behaviour than MSL100

**Comment by krahabb** [comment]
Hello,
This might be similar to this issue (#218) and the pre-release already has it fixed (you'd have to configure HACS to show pre-release versions to install it)
I'm actually working on tons of refactors and tweaks so I don't know when a 'stable' official release would come

**Comment by jscmidt** [comment]
I will test it with more bulbs over the next days, but looks like that fixed it!
