### ISSUE TITLE
Flickering when using in groups

### ISSUE THREAD

**Issue by jscmidt** [krahabb/meross_lan#241]
## Version of the custom_component
Newest

## Configuration
I‘ve added the bulbs via UI, not via YAML 

## Describe the bug
When the Meross bulb is already off an I turn off a group the meross bulb belong to the bulb shortly Fades in without any reason.
I have a video showing the problem:

https://user-images.githubusercontent.com/74502558/205495953-a65284b1-568b-47cc-a09f-8af6f6e4a033.mov

## Debug log
Are there any logs relevant here?

**Comment by krahabb** [comment]
Hello @jscmidt,
I'll be back on this in few days. At first, it seems a 'bug' in HA when it sends the group command but I guess this would be noticed by the thousands of HA users experiencing group switch on/off so I'll take this as a bug in meross_lan anyway and check for clues.
I'll maybe ask you for support when I'll start actively looking at it

Thank you

**Comment by jscmidt** [comment]
I will test it out over the next days, but looks like this is also fixed with the pre Release!
