### ISSUE TITLE
Retrive keys from integration

### ISSUE THREAD

**Issue by Keltere** [krahabb/meross_lan#249]
Hi, i'm currently using homeassistant OS on a VM but because the resources it uses are too high i had to move to docker instead.
Unfortunately because i'm away from home for a long time i cannot access directly the device to redo a configuration from scratch. It's possible to retrieve those keys from the old HA installation and use them directly in the new docker HA?
Thanks.

**Comment by krahabb** [comment]
Hello @Keltere,
Of course the device key is the same for your devices so you can just 'port' the old configured one to the new setup.
If your old VM is still accessible you can just open the integration configuration UI for your meross_lan devices and get the key from there
If the VM is not running anymore, the data for the configuration are stored in (your HA config directory)/.storage/config_entries.
This file contains (all of?) the instance configuration entries ie. every data for integrations you setup by the UI so it might be a bit verbose but you should find the way to the meross_lan specific config(s)

**Comment by Keltere** [comment]
Thank you that solve my issue and i successfully moved to a docker instance.
Great work with this integration.
