### ISSUE TITLE
Problem Release v3.0.0 hub msh300 and mts100v3 not available

### ISSUE THREAD

**Issue by testHAtest** [krahabb/meross_lan#255]
Hello, I have updated to the latest release and the old mts100v3 thermostats have become unavailable, I have one mts150 and it works correctly, Home assistant updated to the latest version.

**Comment by krahabb** [comment]
Hello @testHAtest,
could you provide a [diagnostic](https://github.com/krahabb/meross_lan/wiki/Diagnostics#download-diagnostics) of the hub device ?

**Comment by testHAtest** [comment]
sorry, it solves like this: On 3.0.0 you should enter the integration configuration for each device and set the proper key.
