### ISSUE TITLE
Meross MSS210 (UK) Green LED constantly blinking!

### ISSUE THREAD

**Issue by thestraycat** [krahabb/meross_lan#276]
**Issue:** 
Meross MSS210 plug LED constantly blinks when the plug is turned on.

**Configuration**
Meross MSS210  Added the plug via Android pairer App -> using User ID / Key method ->  HomeAssistant Mosquitto broker.

**Details**
- I can turn off the LED via the discovered "dnd" switch but then i have no identification that the plug is on/off by physically looking at it.
- Although the plug is blinking, it dosn't seem to be in a pairing mode as its WIFI AP is not discoverable via my android phone.

Not sure if the firmware is v4.0.0 or v4.2.5 as per the screenshot??

![image](https://user-images.githubusercontent.com/9296295/232134240-fab4546c-3d38-4d35-9001-390973849243.png)

Details from config_meross_lan,txt from Home Assistant:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.4.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.04.0",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "meross_lan": {
      "version": "3.0.3",
      "requirements": []
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
"integration_manifest": {
    "domain": "meross_lan",
    "name": "Meross LAN",
    "after_dependencies": [
      "mqtt",
      "dhcp",
      "recorder",
      "persistent_notification"
    ],
    "codeowners": [
      "@krahabb"
    ],
    "config_flow": true,
    "dhcp": [
      {
        "hostname": "*",
        "macaddress": "48E1E9*"
      },
      {
        "hostname": "*",
        "macaddress": "34298F1*"
      },
      {
        "registered_devices": true
      }
    ],
    "documentation": "https://github.com/krahabb/meross_lan",
    "integration_type": "hub",
    "iot_class": "local_polling",
    "issue_tracker": "https://github.com/krahabb/meross_lan/issues",
    "loggers": [
      "custom_components.meross_lan"
    ],
    "mqtt": [
      "/appliance/+/publish"
    ],
    "requirements": [],
    "version": "3.0.3",
    "is_built_in": false
  },
  "data": {
    "host": "**REDACTED**",
    "key": "**REDACTED**",
    "cloud_key": null,
    "protocol": null,
    "polling_period": null,
    "trace_timeout": null,
    "device_id": "**REDACTED**",
    "payload": {
      "all": {
        "system": {
          "hardware": {
            "type": "mss210",
            "subType": "us",
            "version": "4.0.0",
            "chipType": "MT7686",
            "uuid": "################################",
            "macAddress": "#################"
          },
          "firmware": {
            "version": "4.2.5",
            "homekitVersion": "2.0.1",
            "compileTime": "Sep  1 2021 14:23:40",
            "encrypt": 1,
            "wifiMac": "#################",
            "innerIp": "#############",
            "server": "#############",
            "port": "####",
            "userId": "#"
          },

**Comment by thestraycat** [comment]
OK. 

So i can connect fine to my Mosquitto instance on port 8883 using TLS encryption. So i know there is no issue there, But i cant get the "pairer app" to connect to my MQTT broker during configuration.

What else can i test?

**Comment by krahabb** [comment]
Hello @thestraycat,
I see you are likely involved in some new mosquitto config [nightmares](https://github.com/krahabb/meross_lan/discussions/63#discussioncomment-5621513) and I can't really add anything more here but the blinking is usually the mqtt registration phase (this only confirms your device mqtt connection issues)

**Comment by thestraycat** [comment]
@krahabb  - Hi there! Yes that's right.

I have local http control of the plug
However no matter what i configure in Mosquitto v6.2 i can't get the plug to talk to the broker in HomeAssistant :(

* I've tried the pairer app
* I've tried the node scripts to send the pairing command

Nothing works. Is this simply because Mosquitto v6.2 wont allow the communication due to breaking changes? What version and setup do you run?
