### ISSUE TITLE
"Opening" doesn't trigger the automation anymore

### ISSUE THREAD

**Issue by ams3401** [krahabb/meross_lan#283]
HA ver: 2023.4.6
Hardware: MSG100 4.0.0 (Firmware 4.2.5)

<img width="394" alt="Screenshot 2023-04-25 at 4 30 28 PM" src="https://user-images.githubusercontent.com/70864968/234418398-a40487b3-bf55-47af-a19e-bc63dc59d7a7.png">

Opening the garage door does turn my garage door card status to "Opening" but, using 
```
platform: state
entity_id:
  - cover.garage_garage
from: closed
to: opening
```
does not trigger the automation unlike it used to.

I bypassed the issue temporarily by using "Opened" instead of "Opening" using
```
platform: device
device_id: f9e60855a26b3bb221030d56ffb73ace
domain: cover
entity_id: cover.garage_garage
type: opened
```
but this results delay in my notification automation since it does not get triggered until the garage door is fully "Opened"

Am I the only one facing this issue?

**Comment by krahabb** [comment]
That looks like a bug in HA automation engine since if you see the correct state change in logbook and history  then the integration is working good.

Could it be that?

**Comment by ams3401** [comment]
> 

I haven't had a chance to run a debug yet and I didn't want to go through the trial and error so I kinda added all possible status under the variable and it seems to have resolved the issue:
```
platform: state
entity_id:
  - cover.garage_garage
to:
  - opening
  - open
  - opened
```
