### ISSUE TITLE
manifest.json - loggers entry correct?

### ISSUE THREAD

**Issue by andreash** [krahabb/meross_lan#296]
I found 
  "loggers": ["custom_components.meross_lan"],
in manifest.json. meross_lan would not be activated and generates an error message, that the control flow could not beloaded with respect to custom_components.meross_lan.
I change the entry to 
  "loggers": ["custom_components/meross_lan"] 
and then it worked.
Might this be a bug?

**Comment by krahabb** [comment]
Hello @andreash,
When I've first configured the entry in the manifest and tested the functioning everything was looking good. At the moment I can't immediately review and verify but an issue is there for sure if your fix works.
Maybe something changed in between inside the HA core

**Comment by krahabb** [comment]
Back on this:
I'm actually able to use the 'default' (custom_components.meross_lan) configuration in manifest.json without any issue, at least none I can see.
Are you still experiencing this issue ?
What I do to test it is to just enable the debug logging for the integration from the HA UI and see that debug logs are correctly dumped in home_assistant.log
