### ISSUE TITLE
Device has no device or entity 

### ISSUE THREAD

**Issue by dorr14** [krahabb/meross_lan#297]
I have a number of Meross Lan devices on the go set up through the HACS Meross LAN integration. We recently had an outage on the WIFI and I have managed to get everything working again apart from 1 310 smart socket attached to the kettle. It have installed it the same way as all the other and cross referenced the IP from the router which is also set to static on all my LAN devices on the router setting. I have also redone the device on the meross app directly but still doesn't recognise it in HA. It works perfectly in the app directly so the socket seems to be in working order and is set up exactly the same way as 8 other Meross LAN devices so not sure what needs to be tweaked.

Has anyone come across this issue or have any other way of getting a reliable feed to HA? I have the IOT for Meross too which does work but it is temperamental at times. 

![Screenshot_20230613_063518_Home Assistant](https://github.com/krahabb/meross_lan/assets/109535705/2ac762b1-cbe5-48da-9d36-e17a0e798545)

**Comment by dorr14** [comment]
> y first guess is the initialization code fails to manage the device setup but there should be a log for this

Thanks for getting back to me, it does not produce an entity so it doesn't show on the log book. Do you know where I can find a log for the action when I try to set it up?

**Comment by krahabb** [comment]
I'll have to check this with latest HA core 2023.6.x since the newer UI might behave differently from the legacy one...

Itcould even be a bug in core itself or sometimes I've seen this happening when the meross_lan component files were corrupted somehow. 
Even if maybe useless, a re-download of the meross_lan integration from HACS could fix the issue

**Comment by dorr14** [comment]
> I'll have to check this with latest HA core 2023.6.x since the newer UI might behave differently from the legacy one...
> 
> Itcould even be a bug in core itself or sometimes I've seen this happening when the meross_lan component files were corrupted somehow. Even if maybe useless, a re-download of the meross_lan integration from HACS could fix the issue

I redownload the HACS, restarted HA and it appeared perfectly, thanks for the tip.
