### ISSUE TITLE
Old MSS510 not adding

### ISSUE THREAD

**Issue by meisanerd** [krahabb/meross_lan#30]
I am attempting to connect to some fairly old MSS510s (hardware version 1.0.0, firmware 1.1.16), and they are throwing python errors and not adding the entities to Home Assistant.

Error message is below:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/meross_lan/__init__.py", line 75, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, device.platforms.keys())
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

I have them currently connected to Meross Cloud (as MQTT setup is also being a pain in the butt...), and have configured Meross LAN to access them via HTTP on an IP Address that is statically assigned via my DHCP server.

**Comment by krahabb** [comment]
Hello @meisanerd,
It looks like the error is in a 'missing' Home Assistant api call ('async_setup_platform'). I've probably started using some new methods while my integration manifest still claims compatibility with HA version 2020.0.0. 
That call was added to home assistant core some 2 months ago so if your HA version is older than that, this is the reason
Shame on me for that. I will revert that code to something safer for the next release (or bump the required HA version :)

**Comment by meisanerd** [comment]
Derp, my bad, I usually make sure I am running the latest codebase before filing a bug, but I spent the past 2 days fighting with the stupid thing, and was in a hurry to just get access to it from HA...  I was literally 1 version too old...

Updated to the latest home assistant, and it is properly adding now.  Thanks.

**Comment by krahabb** [comment]
Thank you. 
my bad too since I should test it a bit against 'not so old' cores
All good anyway!
