### ISSUE TITLE
Meross Smart Switch (mss310, mss315, mss-any) power and energy readings failure

### ISSUE THREAD

**Issue by PhilippeRaven** [krahabb/meross_lan#300]
## Version of the custom_component
v4.2.0

## Configuration

3x MSS310 with 6.1.10 firmware
1x MSS310 with 6.3.21 firmware

## Describe the bug
I upgraded the custom_component from 2.6.2 to 4.2.0 to be sure it will work with the new MSS310 I just bought, with firmware 6.3.21.
So currently in 4.2.0, everything is still working perfectly for the 3 MSS310 with 6.1.10, BUT for the one with 6.3.21, I can on/off the outlet and the DNDmode, but I got no data from the consumption : 
- no current value
- no energy value
- no power value
- no voltage value

I'm using the MQTT way.

## Debug log
Currently no logs.
I'll try tonight to see a difference in MQTT messages between the 3 working and the one not working.

**Comment by PhilippeRaven** [comment]
Well, suddenly today, since 7:48AM, I got values.
I don't understand how and why it was not working before, but it works now.
I hope it'll keep working.

**Comment by krahabb** [comment]
If I'm not wrong, I remember the consumption readings where 'off' (on my older 2.0.0 fw) when the plus was not able to sync it's time. Maybe this could explain this a bit.
meross_lan has a sort of time sync procedure in place with 'cooperative' devices (my mss310 on fw 2.0.0 where...) and should be able to get the device going. The time-sync procedure usually starts at boot with the device asking for a proper time setting reply through the MQTT broker (and meross_lan or whatever software stack is at the other end)

**Comment by PhilippeRaven** [comment]
Hi krahabb, thanks for the reply.
But what could prevent the plug to sync his time (apart from not getting internet access because the preconfigured ntp is on the internet). BTW from which ntpd it got his time ? I've got my own internal ntpd, so if it was possible to configure a specific ntpd like it's possible with the MQTT parameters, that'd be great !

**Comment by krahabb** [comment]
That's not possible as far as I know...
what you could do is to 'proxy' the ntp requests going to the internet by using a private dns configured on the router for your LAN devices and instruct this private DNS server to map the requests going to the outside NTP server names to the IP of your private NTP - which I guess would be the router itself.
At the moment I don't know which 'public' NTPs are searched for by the Meross devices but that could be easily spotted by sniffing your LAN.
[Here](https://github.com/albertogeniola/MerossIot/issues/142#issue-733846468) a better explanation of the scenario

**Comment by krahabb** [comment]
Reopening in order to collect various issues (#312, #318) about the same underlying problem

**Comment by Write** [comment]
I also have a mss310 6.0.0, with Firmware 6.3.21, latest Alpha .1 doesn't fix the issue. 

I have paired mine with a local Mosquitto MQTT Broker and add my MSS310 without device key via the IP + HTTP API (Not sure how to connect via the MQTT one).

All value shows as 0, whereas my older mss310 2.0.0 with firmware 2.1.17 report everything just fine.

Furthermore, I forward all NTP (Port 123) request going outside to my local NTP server. 

I'm not sure how to set the "TimeZone" (as seen here : "configure the MSS310 as MQTT and with TZ in meross_lan" : https://github.com/krahabb/meross_lan/issues/318#issuecomment-1723387029 ).

**Comment by Write** [comment]
This is not fixed.
