### ISSUE TITLE
MSG200: Close / Open door durations not polling status updates

### ISSUE THREAD

**Issue by PowershellScripter** [krahabb/meross_lan#301]
I saw that this issue was posted about one of other garage door models, but I did not see where there was a resolution. I wanted to add not only that this issue is persisting across models, but also add additional information that may help with a resolution is one is not found.

Here is the states they start in when restarting Home Assistant:
![image](https://github.com/krahabb/meross_lan/assets/71091773/893ef2bb-e0ad-4b79-bfcd-6fc0615f9181)

This is the message it shows when I go to one of the entities:
![image](https://github.com/krahabb/meross_lan/assets/71091773/2b0ebccc-c0f5-49b2-9006-85f626b483a1)

But, if I go to my dashboard and hit the button to open and close the garage once, it will then modify the entities and display the correct status.
But, just as someone previously mentioned, the duration always defaults to 35s, when I know for a fact that the durations are 12s. If, I update them manually, they change and work until the next reboot cycle and those entities reset until I push the open and close commands again. 

I have the connection state set to auto and polling every 3 seconds

This is how it shows under states:
![image](https://github.com/krahabb/meross_lan/assets/71091773/0a6a8691-5de9-4f44-8de7-2f7d20bd7130)

Is there any additional information you need me to pull for this or was there ever a solution to fix this?

**Comment by krahabb** [comment]
Hello,
I see the point: actually the MSGXXX have different implemetation(s) (varying by firmware maybe?) for the correct message setup about this parameters and so meross_lan has some sort of euristic in place to try get the correct one...
Of course the results might be 'far from ideal' and they are indeed. I'm actually a bit 'away' from code but I'll try to follow up asap and release a better implementation for this.
In the meantime, could you please get a diagnostic trace for the device so I could inspect it's hw/sw capabilities and try get some more understanding?

**Comment by krahabb** [comment]
A solution for this issue should come in the next release. Thanks to #330 I was able to finally get the info needed to correctly parse the newer firmwares with open/close delays correctly set for each channel
