### ISSUE TITLE
Error key ms3100

### ISSUE THREAD

**Issue by manustars** [krahabb/meross_lan#302]
i have 2 meross 310 and all unaviable, i test for readd but recived "not valid key", then delete the key and select  "recover merros account" but the same error. this a log

`"2023/07/13 - 13:23:47",
        "",
        "auto",
        "LOG",
        "DEBUG",
        "MerossKeyError(Invalid key) in async_http_request GET Appliance.Control.ConsumptionX attempt(0)"
      ],
      [
        "2023/07/13 - 13:23:49",
        "TX",
        "http",
        "GET",
        "Appliance.Control.Electricity",
        {
          "electricity": {}
        }
      ],
      [
        "2023/07/13 - 13:23:49",
        "",
        "auto",
        "LOG",
        "DEBUG",
        "MerossKeyError(Invalid key) in async_http_request GET Appliance.Control.Electricity attempt(0)"
      ],
      [
        "2023/07/13 - 13:23:51",
        "TX",
        "http",
        "GET",
        "Appliance.Control.ConsumptionConfig",
        {
          "consumptionConfig": {}
        }
      ],
      [
        "2023/07/13 - 13:23:51",
        "",
        "auto",
        "LOG",
        "DEBUG",
        "MerossKeyError(Invalid key) in async_http_request GET Appliance.Control.ConsumptionConfig attempt(0)"
      ],
      [
        "2023/07/13 - 13:24:16",
        "",
        "auto",
        "LOG",
        "DEBUG",
        "polling start"
      ],
      [
        "2023/07/13 - 13:24:16",
        "TX",
        "http",
        "GET",
        "Appliance.System.All",
        {
          "all": {}
        }
      ],
      [
        "2023/07/13 - 13:24:16",
        "",
        "auto",
        "LOG",
        "DEBUG",
        "MerossKeyError(Invalid key) in async_http_request GET Appliance.System.All attempt(0)"
      ],
      [
        "2023/07/13 - 13:24:16",
        "",
        "auto",
        "LOG",
        "DEBUG",
        "polling end"
      ],
      [
        "2023/07/13 - 13:26:16",
        "",
        "auto",
        "LOG",
        "DEBUG",
        "polling start"
      ],
      [
        "2023/07/13 - 13:26:16",
        "TX",
        "http",
        "GET",
        "Appliance.System.All",
        {
          "all": {}
        }
      ],
      [
        "2023/07/13 - 13:26:16",
        "",
        "auto",
        "LOG",
        "DEBUG",
        "MerossKeyError(Invalid key) in async_http_request GET Appliance.System.All attempt(0)"
      ],
      [
        "2023/07/13 - 13:26:16",
        "",
        "auto",
        "LOG",
        "DEBUG",
        "polling end"`
and on logger i see this on HTTP Response ""payload":{"error":{"code":5001,"detail":"sign error"}}})"

**Comment by manustars** [comment]
any update for this bug

**Comment by krahabb** [comment]
Hello @manustars,
I'm sorry I can't really tell where the issue lies. As far as the device key is correct this shouldn't happen of course.
Is the meross account you're using to recover the key, the same where the devices are binded?

**Comment by manustars** [comment]
as per your suggestion I ran everything from scratch, I also made another meross account, eliminated integration reboots various ha and now it worked. Thank you so much
