### ISSUE TITLE
Adding a new MS100FH intelligent temperature and humidity sensor from Meross. 

### ISSUE THREAD

**Issue by Aldex-14** [krahabb/meross_lan#303]
There is a new Smart Temperature and Humidity Sensor
MS100FH it would be great if this could be integrated.

**Comment by krahabb** [comment]
Hello @Aldex-14,
I'm personally using an MS100 (legacy version of the same sensor I guess) and it works flawlessly.
If the related Meross Hub is already configured in meross_lan the (sub)device should appear automatically. If not, please send me a trace of the hub device so I could inspect what's going on

**Comment by Aldex-14** [comment]
Hello krahabb,

Here is the sensor I use: [https://www.meross.com/en-gc/smart-sensor/smart-humidity-sensor/143](url)
I am not sure if this is the correct information, but here is the information I can provide:

This error was caused by a custom integration

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:588
Integration: Meross LAN (documentation, issues)
First occurred: 21:50:27 (7 occurrences)
Last logged: 22:02:12

MerossDevice(Meross Smart Hub): MerossSubDevice(Dachzimmer) AttributeError('MerossSubDevice' object has no attribute 'sensor_humidity_latest') in _parse(humidity, {'latest': 409, 'latestSampleTime': 1689709770, 'max': 1000, 'min': 0})
MerossDevice(Meross Smart Hub): MerossSubDevice(Dachzimmer) AttributeError('MerossSubDevice' object has no attribute 'sensor_tempHum_latestTemperature') in _parse(tempHum, {'latestTemperature': 295, 'latestHumidity': 413, 'id': '39000DD28573', 'syncedTime': 1689710372, 'sample': [[299, 366, 1689685095, 1689685697], [300, 367, 1689685697, 1689686299], [299, 367, 1689686299, 1689686901], [299, 368, 1689686901, 1689687503], [298, 369, 1689687503, 1689688706], [299, 365, 1689688706, 1689689308], [298, 366, 1689689308, 1689689910], [298, 367, 1689689910, 1689690512], [299, 366, 1689690512, 1689691114], [300, 365, 1689691114, 1689691716], [300, 367, 1689691716, 1689692318], [301, 365, 1689692318, 1689692920], [301, 367, 1689692920, 1689693522], [303, 366, 1689693522, 1689694125], [303, 367, 1689694125, 1689695328], [302, 365, 1689695328, 1689695930], [302, 366, 1689695930, 1689696532], [302, 365, 1689696532, 1689697134], [303, 366, 1689697134, 1689697735], [303, 362, 1689697735, 1689698939], [303, 363, 1689698939, 1689699541], [303, 365, 1689699541, 1689700142], [304, 363, 1689700142, 1689700744], [303, 363, 1689700744, 1689701346], [303, 364, 1689701346, 1689701947], [304, 366, 1689701947, 1689703151], [305, 367, 1689703151, 1689703753], [305, 370, 1689703753, 1689704354], [304, 369, 1689704354, 1689704956], [305, 370, 1689704956, 1689705558], [305, 372, 1689705558, 1689706160], [304, 375, 1689706160, 1689706762], [302, 367, 1689706762, 1689707063], [299, 363, 1689707063, 1689707665], [298, 372, 1689707665, 1689707965], [295, 382, 1689707965, 1689708567], [293, 394, 1689708567, 1689709169], [293, 403, 1689709169, 1689709770], [294, 409, 1689709770, 1689710372], [295, 413, 1689710372, -10000]], 'latestTime': 1689710372})
MerossDevice(Meross Smart Hub): MerossSubDevice(Dachzimmer) AssertionError((channel, entitykey) is not unique inside manager.entities) in _parse(temperature, {'latest': 295, 'latestSampleTime': 1689710372, 'max': 500, 'min': -100})
MerossDevice(Meross Smart Hub): MerossSubDevice(Dachzimmer) AssertionError((channel, entitykey) is not unique inside manager.entities) in _parse(humidity, {'latest': 413, 'latestSampleTime': 1689710372, 'max': 1000, 'min': 0})
MerossDevice(Meross Smart Hub): MerossSubDevice(Dachzimmer) AssertionError((channel, entitykey) is not unique inside manager.entities) in _parse(tempHum, {'id': '39000DD28573', 'latestTemperature': 295, 'latestHumidity': 413, 'latestTime': 1689710372, 'sample': [[299, 366, 1689685095, 1689685697], [300, 367, 1689685697, 1689686299], [299, 367, 1689686299, 1689686901], [299, 368, 1689686901, 1689687503], [298, 369, 1689687503, 1689688706], [299, 365, 1689688706, 1689689308], [298, 366, 1689689308, 1689689910], [298, 367, 1689689910, 1689690512], [299, 366, 1689690512, 1689691114], [300, 365, 1689691114, 1689691716], [300, 367, 1689691716, 1689692318], [301, 365, 1689692318, 1689692920], [301, 367, 1689692920, 1689693522], [303, 366, 1689693522, 1689694125], [303, 367, 1689694125, 1689695328], [302, 365, 1689695328, 1689695930], [302, 366, 1689695930, 1689696532], [302, 365, 1689696532, 1689697134], [303, 366, 1689697134, 1689697735], [303, 362, 1689697735, 1689698939], [303, 363, 1689698939, 1689699541], [303, 365, 1689699541, 1689700142], [304, 363, 1689700142, 1689700744], [303, 363, 1689700744, 1689701346], [303, 364, 1689701346, 1689701947], [304, 366, 1689701947, 1689703151], [305, 367, 1689703151, 1689703753], [305, 370, 1689703753, 1689704354], [304, 369, 1689704354, 1689704956], [305, 370, 1689704956, 1689705558], [305, 372, 1689705558, 1689706160], [304, 375, 1689706160, 1689706762], [302, 367, 1689706762, 1689707063], [299, 363, 1689707063, 1689707665], [298, 372, 1689707665, 1689707965], [295, 382, 1689707965, 1689708567], [293, 394, 1689708567, 1689709169], [293, 403, 1689709169, 1689709770], [294, 409, 1689709770, 1689710372], [295, 413, 1689710372, -10000]]})

**Comment by krahabb** [comment]
Hello @Aldex-14,
It looks like this newer sensor presents itself in a slightly different way so meross_lan is not able to correctly detect it.
In order to proceed I would need a ['diagnostic trace'](https://github.com/krahabb/meross_lan/wiki/Diagnostics#download-diagnostics) of the releated hub device

**Comment by krahabb** [comment]
Hello @Aldex-14 ,
did you tried the sensor with latest Cloudy.3 ? And if so, did it work?
I'll consider the issue closed but feel free to reopen it in case
