### ISSUE TITLE
Integration not found in HACS

### ISSUE THREAD

**Issue by pc-bastler** [krahabb/meross_lan#324]
**Describe the bug**
I am trying to install the Integration to my Home Assistant but it is not found in HACS (V 1.33.0).
I am not firm enough to try a manual installation.

**Your environment**
HomeAssistant version: 2023.10.1
Hassio Version (if applicable): 10.5
Hardware environment: Raspberry PI 3B+ connected via LAN.
![Bildschirmfoto 2023-10-08 um 19 14 28](https://github.com/krahabb/meross_lan/assets/46841479/abde4dfc-bce6-43cb-9386-2f7f9d7462ab)

**Comment by krahabb** [comment]
Weird...I'll take a look at the issue but I have no notice it was withdrawn recently ;)

**Comment by pc-bastler** [comment]
Please let me know, if you need any information.
Your Integration is not the only one I have this problem with... I also tried meross-homeassist, I got the same issue there.
Other addons I can see in the HACS Store, so it's not an issue that I cannot retrieve anything via HACS.

**Comment by krahabb** [comment]
I've checked the official HACS default repositories list and `meross_lan` is still there.

Looking at your snapshot I can't reproduce the same UI layout so I don't really know which search feature you are using (I'm testing on HACS 1.33 - HA 2023.9.3). In my setup, after entering the main HACS page, I go to 'Integrations' and then hit the 'Explore & Download repositories' button floating in the lower right corner of the UI...

**Comment by GeorgeCaliment** [comment]
Hi @pc-bastler, think posting also your HACS configuration could help, you can get it from HA integrations page.

**Comment by garysargentpersonal** [comment]
@krahabb I just found this which is very odd! https://github.com/hacs/integration/issues/3325

Not sure why someone was requesting the removal of your integration, but looks like it was denied anyway.

**Comment by GeorgeCaliment** [comment]
@garysargentpersonal I don't think this is the reason, cause most of us can see the repo, and the request above was denied.

**Comment by Tech4c** [comment]
Go to Settings > Devices & services > HACS > Configuration > Filter with country code = select ALL
