### ISSUE TITLE
Add support for mss570x three way dimmer switch

### ISSUE THREAD

**Issue by 7h3ju57** [krahabb/meross_lan#325]
**Is your feature request related to a problem? Please describe.**
Just started using this addon and so far has worked great. Thing is, that when i attempt to turn on the mss570x dimmer switch, it will blink once. It does this every time the light gets turned on using the addon. Works fine using the meross app and the meross IOT cloud addon. It would be great to be able to only use meross lan and remove the cloud dependency for all my switches. I can provide logs and testing if needed.

**Describe the solution you'd like**
Add support for mss570x, find reason or fix for switch flashing light once when turning switch on.

**Describe alternatives you've considered**
Meross iot cloud 

[merosslan2.log](https://github.com/krahabb/meross_lan/files/12909900/merosslan2.log)

**Comment by krahabb** [comment]
This is likely the same as #218.
It was obviously not fixed...but I'm working on a possible better patch ...
Keep in touch!

**Comment by 7h3ju57** [comment]
> This is likely the same as #218. It was obviously not fixed...but I'm working on a possible better patch ... Keep in touch!

Looks about right. Let me know if you'd like to test anything out

**Comment by simbo1984** [comment]
@krahabb It is working with the dimmers now! Good job 👍🏻

**Comment by 7h3ju57** [comment]
Working great on aloha. Thanks for the fix!

**Comment by 7h3ju57** [comment]
@krahabb  lights are blinking again when turning on, was introduced in the latest update 4.5.1
Rolled back to version 4.5.0 no blinking.

**Comment by 7h3ju57** [comment]
I think the issue may have returned.
If I turn on a light only, works great. If I try to turn on and set brightness within the service call it will flash when turning on. Oddly, within an automation, if I turn on the light, delay 1 second and then change brightness, it works great again.

**Comment by krahabb** [comment]
I think the problem lies in the 'fast' sequence : turn-on and then set-brightness you achieve when issuing the commands in an automation.
This is exactly 'the same error' the component was doing at the time the bug was discovered. After that, I've put some checks and logic in order to (almost) never have to send that sequence back-to-back

Wouldn't it be possible to use only set-brightness in automation? that should already turn on the device

**Comment by 7h3ju57** [comment]
I'm not sure I can only set the brightness. There are three service calls for lights, turn on, turn off and toggle.
If you choose device, you do have an option to increase or decrease brightness but no way of setting it. If you know of another way, I'm open to suggestions.

**Comment by krahabb** [comment]
I'm pretty sure you can pass in the 'luminance' or 'brightness' (didnt check the docs..) parameter to the turn_on service call. The code, in fact, just receives the turn_on call with (eventual) paramters set by the service call itself.
For example when you change the rgb or any other feature from UI, it is always conveyed as a turn_on with all the settings carried over as dynamic parameters
