### ISSUE TITLE
Integration MS400 Smart Water Leak Sensor

### ISSUE THREAD

**Issue by rosti76** [krahabb/meross_lan#332]
MS400 Smart Water Leak Sensor reports only Battery state an no value for Alarm

Here the debug if an alarm triggering at 20:17:41   "latestWaterLeak": **1**

2023/11/15 - 20:16:18		auto	GETACK	Appliance.System.All	{"system": {"hardware": {"type": "msh300hk", "subType": "un", "version": "5.0.0", "chipType": "MT7686", "uuid": "###############################0", "macAddress": "################0"}, "firmware": {"version": "5.5.32", "homekitVersion": "4.1", "compileTime": "2023/10/11 11:31:05 GMT +08:00", "encrypt": 1, "wifiMac": "################0", "innerIp": "############0", "server": "#################0", "port": "@0", "userId": "@0"}, "time": {"timestamp": 1700074476, "timezone": "Europe/Vienna", "timeRule": [[1698541200, 3600, 0], [1711846800, 7200, 1], [1729990800, 3600, 0], [1743296400, 7200, 1], [1761440400, 3600, 0], [1774746000, 7200, 1], [1792890000, 3600, 0], [1806195600, 7200, 1], [1824944400, 3600, 0], [1837645200, 7200, 1], [1856394000, 3600, 0], [1869094800, 7200, 1], [1887843600, 3600, 0], [1901149200, 7200, 1], [1919293200, 3600, 0], [1932598800, 7200, 1], [1950742800, 3600, 0], [1964048400, 7200, 1], [1982797200, 3600, 0], [1995498000, 7200, 1]]}, "online": {"status": 1, "bindId": "aDIlggbTqFQB9f1E", "who": 1}}, "digest": {"hub": {"hubId": 3922622114, "mode": 0, "nvdmChl": 0, "workChl": 3, "curChl": 3, "subdevice": [{"id": "28004D9D7DED", "status": 1, "lastActiveTime": 0, "smokeAlarm": {"status": 170, "lmTime": 0, "interConn": 0}}, {"id": "150010206190", "status": 1, "onoff": 0, "lastActiveTime": 1700074352, "waterLeak": {"latestWaterLeak": 0, "latestSampleTime": 0}}, {"id": "1500102061CB", "status": 1, "onoff": 0, "lastActiveTime": 1700074473, "waterLeak": {"latestWaterLeak": 0, "latestSampleTime": 0}}, {"id": "150010206084", "status": 1, "onoff": 0, "lastActiveTime": 1700074442, "waterLeak": {"latestWaterLeak": 0, "latestSampleTime": 0}}]}}}
2023/11/15 - 20:16:18		auto	GETACK	Appliance.System.Ability	{"Appliance.Config.Key": {}, "Appliance.Config.WifiList": {}, "Appliance.Config.Wifi": {}, "Appliance.Config.WifiX": {}, "Appliance.Config.Trace": {}, "Appliance.Config.Info": {}, "Appliance.System.All": {}, "Appliance.System.Hardware": {}, "Appliance.System.Firmware": {}, "Appliance.System.Debug": {}, "Appliance.System.Online": {}, "Appliance.System.Time": {}, "Appliance.System.Clock": {}, "Appliance.System.Ability": {}, "Appliance.System.Runtime": {}, "Appliance.System.Report": {}, "Appliance.System.Position": {}, "Appliance.System.DNDMode": {}, "Appliance.Control.Multiple": {"maxCmdNum": 5}, "Appliance.Control.Bind": {}, "Appliance.Control.Unbind": {}, "Appliance.Control.Upgrade": {}, "Appliance.Hub.Online": {}, "Appliance.Hub.ToggleX": {}, "Appliance.Hub.SubdeviceList": {}, "Appliance.Hub.Battery": {}, "Appliance.Hub.Sensitivity": {}, "Appliance.Hub.PairSubDev": {}, "Appliance.Hub.Report": {}, "Appliance.Hub.Mts100.All": {}, "Appliance.Hub.Mts100.Temperature": {}, "Appliance.Hub.Mts100.ScheduleB": {"scheduleUnitTime": 15}, "Appliance.Hub.Mts100.Mode": {}, "Appliance.Hub.Mts100.Adjust": {}, "Appliance.Hub.Mts100.SuperCtl": {}, "Appliance.Hub.Mts100.Config": {}, "Appliance.Hub.SubDevice.MotorAdjust": {}, "Appliance.Hub.SubDevice.Beep": {}, "Appliance.Hub.SubDevice.Version": {}, "Appliance.Hub.Sensor.All": {}, "Appliance.Hub.Sensor.WaterLeak": {}, "Appliance.Hub.Sensor.TempHum": {}, "Appliance.Hub.Sensor.Adjust": {}, "Appliance.Hub.Sensor.Motion": {}, "Appliance.Hub.Sensor.DoorWindow": {}, "Appliance.Hub.Sensor.Smoke": {}, "Appliance.Hub.Sensor.Alert": {}}
2023/11/15 - 20:16:18	TX	http	GET	Appliance.Config.Info	{"info": {}}
2023/11/15 - 20:16:18	RX	http	GETACK	Appliance.Config.Info	{"info": {"homekit": {"model": "MSH300HK", "sn": "620802230702189", "category": 2, "setupId": "KMN0", "setupCode": "704-07-159", "uuid": "###################################1", "token": "#######################################################################################################################################################################################################################################0"}}}
2023/11/15 - 20:16:18		auto	LOG	DEBUG	handler undefined for method:(GETACK) namespace:(Appliance.Config.Info) payload:({'info': {'homekit': {'model': 'MSH300HK', 'sn': '620802230702189', 'category': 2, 'setupId': 'KMN0', 'setupCode': '704-07-159', 'uuid': '23070500-2623-a00b-d458-e721a1b119f0', 'token': 'MYGpME4CAQECAQEERjBEAiAw1Zj1Q0xj3ssgAgLM+AKLNAX2MBe1jpSnbfGLlgfrMAIgNbVmF+ZZYByMoi8tmbf/wsdRWw+0UXTm7khw/nv/244wVwIBAgIBAQRPMU0wCQIBZgIBAQQBATAQAgFlAgEBBAg4rmsjiQEAADAUAgIAyQIBAQQLMjUzNjY4LTAwNDcwGAIBZwIBAQQQCodenvxHTiy2hU/fAbqJAw=='}}})
2023/11/15 - 20:16:20	TX	http	GET	Appliance.System.Runtime	{"runtime": {}}
2023/11/15 - 20:16:20	RX	http	GETACK	Appliance.System.Runtime	{"runtime": {"signal": 81}}
2023/11/15 - 20:16:22	TX	http	GET	Appliance.System.Position	{"position": {}}
2023/11/15 - 20:16:22	RX	http	GETACK	Appliance.System.Position	{"position": {"longitude": 0, "latitude": 0}}
2023/11/15 - 20:16:22		auto	LOG	DEBUG	handler undefined for method:(GETACK) namespace:(Appliance.System.Position) payload:({'position': {'longitude': 0, 'latitude': 0}})
2023/11/15 - 20:16:22		auto	LOG	DEBUG	polling start
2023/11/15 - 20:16:22	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:16:22	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:16:22	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:16:22	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:16:22		auto	LOG	DEBUG	polling end
2023/11/15 - 20:16:24	TX	http	GET	Appliance.Hub.Online	{"online": []}
2023/11/15 - 20:16:24	RX	http	GETACK	Appliance.Hub.Online	{"online": [{"id": "28004D9D7DED", "status": 1, "lastActiveTime": 0}, {"id": "150010206190", "status": 1, "lastActiveTime": 1700075567}, {"id": "1500102061CB", "status": 1, "lastActiveTime": 1700075688}, {"id": "150010206084", "status": 1, "lastActiveTime": 1700075706}]}
2023/11/15 - 20:16:26	TX	http	GET	Appliance.Hub.ToggleX	{"toggleX": []}
2023/11/15 - 20:16:26	RX	http	GETACK	Appliance.Hub.ToggleX	{"togglex": [{"id": "28004D9D7DED", "onoff": 1}, {"id": "150010206190", "onoff": 0}, {"id": "1500102061CB", "onoff": 0}, {"id": "150010206084", "onoff": 0}]}
2023/11/15 - 20:16:28	TX	http	GET	Appliance.Hub.Battery	{"battery": []}
2023/11/15 - 20:16:28	RX	http	GETACK	Appliance.Hub.Battery	{"battery": [{"id": "28004D9D7DED", "value": 100}, {"id": "150010206190", "value": 100}, {"id": "1500102061CB", "value": 100}, {"id": "150010206084", "value": 100}]}
2023/11/15 - 20:16:30	TX	http	GET	Appliance.Hub.Sensitivity	{"sensitivity": []}
2023/11/15 - 20:16:30	RX	http	GETACK	Appliance.Hub.Sensitivity	{"sensitivity": []}
2023/11/15 - 20:16:30		auto	LOG	DEBUG	handler undefined for method:(GETACK) namespace:(Appliance.Hub.Sensitivity) payload:({'sensitivity': []})
2023/11/15 - 20:16:32	TX	http	GET	Appliance.Hub.Mts100.All	{"all": []}
2023/11/15 - 20:16:32	RX	http	GETACK	Appliance.Hub.Mts100.All	{"all": []}
2023/11/15 - 20:16:32		auto	LOG	DEBUG	polling start
2023/11/15 - 20:16:32	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:16:32	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:16:32	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:16:32	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:16:32		auto	LOG	DEBUG	polling end
2023/11/15 - 20:16:34	TX	http	GET	Appliance.Hub.Mts100.Temperature	{"temperature": []}
2023/11/15 - 20:16:34	RX	http	GETACK	Appliance.Hub.Mts100.Temperature	{"temperature": []}
2023/11/15 - 20:16:36	TX	http	GET	Appliance.Hub.Mts100.ScheduleB	{"schedule": []}
2023/11/15 - 20:16:36	RX	http	GETACK	Appliance.Hub.Mts100.ScheduleB	{"schedule": []}
2023/11/15 - 20:16:38	TX	http	GET	Appliance.Hub.Mts100.Mode	{"mode": []}
2023/11/15 - 20:16:38	RX	http	GETACK	Appliance.Hub.Mts100.Mode	{"mode": []}
2023/11/15 - 20:16:40	TX	http	GET	Appliance.Hub.Mts100.Adjust	{"adjust": []}
2023/11/15 - 20:16:40	RX	http	GETACK	Appliance.Hub.Mts100.Adjust	{"adjust": []}
2023/11/15 - 20:16:42	TX	http	GET	Appliance.Hub.Mts100.SuperCtl	{"superCtl": []}
2023/11/15 - 20:16:42	RX	http	GETACK	Appliance.Hub.Mts100.SuperCtl	{"superCtl": []}
2023/11/15 - 20:16:42		auto	LOG	DEBUG	handler undefined for method:(GETACK) namespace:(Appliance.Hub.Mts100.SuperCtl) payload:({'superCtl': []})
2023/11/15 - 20:16:42		auto	LOG	DEBUG	polling start
2023/11/15 - 20:16:42	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:16:42	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:16:42	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:16:42	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:16:42		auto	LOG	DEBUG	polling end
2023/11/15 - 20:16:44	TX	http	GET	Appliance.Hub.Mts100.Config	{"config": []}
2023/11/15 - 20:16:44	RX	http	GETACK	Appliance.Hub.Mts100.Config	{"config": []}
2023/11/15 - 20:16:44		auto	LOG	DEBUG	handler undefined for method:(GETACK) namespace:(Appliance.Hub.Mts100.Config) payload:({'config': []})
2023/11/15 - 20:16:46	TX	http	GET	Appliance.Hub.SubDevice.MotorAdjust	{"adjust": []}
2023/11/15 - 20:16:46	RX	http	ERROR	Appliance.Hub.SubDevice.MotorAdjust	{"error": {"code": 5000}}
2023/11/15 - 20:16:46		auto	LOG	WARNING	protocol error: namespace = 'Appliance.Hub.SubDevice.MotorAdjust' payload = '{"error": {"code": 5000}}'
2023/11/15 - 20:16:48	TX	http	GET	Appliance.Hub.SubDevice.Beep	{"beep": []}
2023/11/15 - 20:16:48	RX	http	ERROR	Appliance.Hub.SubDevice.Beep	{"error": {"code": 5000}}
2023/11/15 - 20:16:48		auto	LOG	WARNING	protocol error: namespace = 'Appliance.Hub.SubDevice.Beep' payload = '{"error": {"code": 5000}}'
2023/11/15 - 20:16:50	TX	http	GET	Appliance.Hub.SubDevice.Version	{"version": []}
2023/11/15 - 20:16:50	RX	http	GETACK	Appliance.Hub.SubDevice.Version	{"version": []}
2023/11/15 - 20:16:50		auto	LOG	DEBUG	handler undefined for method:(GETACK) namespace:(Appliance.Hub.SubDevice.Version) payload:({'version': []})
2023/11/15 - 20:16:52	TX	http	GET	Appliance.Hub.Sensor.All	{"all": []}
2023/11/15 - 20:16:52	RX	http	GETACK	Appliance.Hub.Sensor.All	{"all": [{"id": "150010206190", "online": {"status": 1, "lastActiveTime": 1700075567}, "waterLeak": {"latestWaterLeak": 0, "latestSampleTime": 0}}, {"id": "1500102061CB", "online": {"status": 1, "lastActiveTime": 1700075688}, "waterLeak": {"latestWaterLeak": 0, "latestSampleTime": 0}}, {"id": "150010206084", "online": {"status": 1, "lastActiveTime": 1700075706}, "waterLeak": {"latestWaterLeak": 0, "latestSampleTime": 1700075250}}, {"id": "28004D9D7DED", "online": {"status": 1, "lastActiveTime": 0}, "smokeAlarm": {"status": 170, "lmtime": 0, "interConn": 0}}]}
2023/11/15 - 20:16:52		auto	LOG	DEBUG	polling start
2023/11/15 - 20:16:52	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:16:52	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:16:52	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:16:52	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:16:52		auto	LOG	DEBUG	polling end
2023/11/15 - 20:16:54	TX	http	GET	Appliance.Hub.Sensor.WaterLeak	{"waterLeak": []}
2023/11/15 - 20:16:54	RX	http	GETACK	Appliance.Hub.Sensor.WaterLeak	{"waterLeak": [{"id": "150010206190", "latestWaterLeak": 0, "latestSampleTime": 0, "sample": []}, {"id": "1500102061CB", "latestWaterLeak": 0, "latestSampleTime": 0, "sample": []}, {"id": "150010206084", "latestWaterLeak": 0, "latestSampleTime": 1700075250, "sample": [[1, 1700074689], [0, 1700074700], [1, 1700075169], [0, 1700075209], [1, 1700075218], [0, 1700075250]]}]}
2023/11/15 - 20:16:54		auto	LOG	DEBUG	handler undefined for method:(GETACK) namespace:(Appliance.Hub.Sensor.WaterLeak) payload:({'waterLeak': [{'id': '150010206190', 'latestWaterLeak': 0, 'latestSampleTime': 0, 'sample': []}, {'id': '1500102061CB', 'latestWaterLeak': 0, 'latestSampleTime': 0, 'sample': []}, {'id': '150010206084', 'latestWaterLeak': 0, 'latestSampleTime': 1700075250, 'sample': [[1, 1700074689], [0, 1700074700], [1, 1700075169], [0, 1700075209], [1, 1700075218], [0, 1700075250]]}]})
2023/11/15 - 20:16:56	TX	http	GET	Appliance.Hub.Sensor.TempHum	{"tempHum": []}
2023/11/15 - 20:16:56	RX	http	GETACK	Appliance.Hub.Sensor.TempHum	{"tempHum": []}
2023/11/15 - 20:16:58	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:16:58	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:00	TX	http	GET	Appliance.Hub.Sensor.Motion	{"motion": []}
2023/11/15 - 20:17:00	RX	http	GETACK	Appliance.Hub.Sensor.Motion	{"motion": []}
2023/11/15 - 20:17:00		auto	LOG	DEBUG	handler undefined for method:(GETACK) namespace:(Appliance.Hub.Sensor.Motion) payload:({'motion': []})
2023/11/15 - 20:17:02	TX	http	GET	Appliance.Hub.Sensor.DoorWindow	{"doorWindow": []}
2023/11/15 - 20:17:02	RX	http	GETACK	Appliance.Hub.Sensor.DoorWindow	{"doorWindow": []}
2023/11/15 - 20:17:02		auto	LOG	DEBUG	polling start
2023/11/15 - 20:17:02	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:17:02	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:17:02	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:02	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:02		auto	LOG	DEBUG	polling end
2023/11/15 - 20:17:04	TX	http	GET	Appliance.Hub.Sensor.Smoke	{"smokeAlarm": []}
2023/11/15 - 20:17:04	RX	http	GETACK	Appliance.Hub.Sensor.Smoke	{"smokeAlarm": [{"id": "28004D9D7DED", "status": 170, "interConn": 0}]}
2023/11/15 - 20:17:06	TX	http	GET	Appliance.Hub.Sensor.Alert	{"alert": []}
2023/11/15 - 20:17:06	RX	http	GETACK	Appliance.Hub.Sensor.Alert	{"alert": []}
2023/11/15 - 20:17:06		auto	LOG	DEBUG	handler undefined for method:(GETACK) namespace:(Appliance.Hub.Sensor.Alert) payload:({'alert': []})
2023/11/15 - 20:17:12		auto	LOG	DEBUG	polling start
2023/11/15 - 20:17:12	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:17:12	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:17:12	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:12	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:12		auto	LOG	DEBUG	polling end
2023/11/15 - 20:17:22		auto	LOG	DEBUG	polling start
2023/11/15 - 20:17:22	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:17:22	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:17:22	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:22	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:22		auto	LOG	DEBUG	polling end
2023/11/15 - 20:17:32		auto	LOG	DEBUG	polling start
2023/11/15 - 20:17:32	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:17:32	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:17:32	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:32	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:32		auto	LOG	DEBUG	polling end
2023/11/15 - 20:17:41	RX	mqtt	PUSH	Appliance.Hub.Sensor.WaterLeak	{"waterLeak": [{"syncedTime": 1700075861, "sample": [[1, 1700075861]], "latestWaterLeak": 1, "latestSampleTime": 1700075861, "id": "150010206190"}]}
2023/11/15 - 20:17:41		auto	LOG	DEBUG	handler undefined for method:(PUSH) namespace:(Appliance.Hub.Sensor.WaterLeak) payload:({'waterLeak': [{'syncedTime': 1700075861, 'sample': [[1, 1700075861]], 'latestWaterLeak': 1, 'latestSampleTime': 1700075861, 'id': '150010206190'}]})
2023/11/15 - 20:17:42		auto	LOG	DEBUG	polling start
2023/11/15 - 20:17:42	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:17:42	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:17:42	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:42	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:42		auto	LOG	DEBUG	polling end
2023/11/15 - 20:17:52		auto	LOG	DEBUG	polling start
2023/11/15 - 20:17:52	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:17:52	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:17:52	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:53	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:17:53		auto	LOG	DEBUG	polling end
2023/11/15 - 20:18:03		auto	LOG	DEBUG	polling start
2023/11/15 - 20:18:03	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:18:03	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:18:03	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:03	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:03		auto	LOG	DEBUG	polling end
2023/11/15 - 20:18:13		auto	LOG	DEBUG	polling start
2023/11/15 - 20:18:13	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:18:13	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:18:13	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:13	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:13		auto	LOG	DEBUG	polling end
2023/11/15 - 20:18:21	RX	mqtt	PUSH	Appliance.Hub.Sensor.WaterLeak	{"waterLeak": [{"syncedTime": 1700075900, "sample": [[1, 1700075861], [0, 1700075900]], "latestWaterLeak": 0, "latestSampleTime": 1700075900, "id": "150010206190"}]}
2023/11/15 - 20:18:21		auto	LOG	DEBUG	handler undefined for method:(PUSH) namespace:(Appliance.Hub.Sensor.WaterLeak) payload:({'waterLeak': [{'syncedTime': 1700075900, 'sample': [[1, 1700075861], [0, 1700075900]], 'latestWaterLeak': 0, 'latestSampleTime': 1700075900, 'id': '150010206190'}]})
2023/11/15 - 20:18:23		auto	LOG	DEBUG	polling start
2023/11/15 - 20:18:23	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:18:23	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:18:23	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:23	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:23		auto	LOG	DEBUG	polling end
2023/11/15 - 20:18:33		auto	LOG	DEBUG	polling start
2023/11/15 - 20:18:33	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:18:33	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:18:33	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:33	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:33		auto	LOG	DEBUG	polling end
2023/11/15 - 20:18:43		auto	LOG	DEBUG	polling start
2023/11/15 - 20:18:43	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:18:43	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:18:43	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:43	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:43		auto	LOG	DEBUG	polling end
2023/11/15 - 20:18:53		auto	LOG	DEBUG	polling start
2023/11/15 - 20:18:53	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}
2023/11/15 - 20:18:53	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}
2023/11/15 - 20:18:53	TX	http	GET	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:53	RX	http	GETACK	Appliance.Hub.Sensor.Adjust	{"adjust": []}
2023/11/15 - 20:18:53		auto	LOG	DEBUG	polling end

**Comment by krahabb** [comment]
It should be doable, I'll see for an implementation in the next days

**Comment by blubbel42** [comment]
We have done this at our home. 2 devices working at the moment. I will see that we do a pull-request ASAP

**Comment by krahabb** [comment]
Thank you, I'll check that but an implementation is already in f9a7888. Please submit the PR anyway so I can eventually mix them (and likely learn a different approach)
