### ISSUE TITLE
MSS310 HW 2.0.0 vs 8.0.0

### ISSUE THREAD

**Issue by mafmafmafmaf** [krahabb/meross_lan#336]
Hi, I have four of these plugs, HW 2.0.0 FW 2.1.17. They've been working rock solid for over a year both in the Meross app and in HA (unlike my five MRS100, which have been driving me crazy for the last month with their totally random disconnects and reconnects only in HA, and for which none of the solutions mentioned here work, but I digress). The Meross app says their FW is up to date, but HA offers to upgrade (and then the update button does nothing, but I digress again).

Recently, I connected a fifth MSS310, and this one is HW 8.0.0 FW 6.3.22.

Here's the issue: everything works under MQTT (Mosquitto). I found that if I disable "Allow cloud MQTT publish" in my cloud profile, the newer plug is disconnected from HA (and so are the shutters), but the older plugs keep going. I can then reconnect the plug (and the shutters) by using them on the Meross app, but they quicly disconnect again if that option is not reenabled.

Also, probably the same issue: all the plugs have instant and zero-wait responses both in the Meross app and in HA, EXCEPT the newer plug imposes an exact 12-second wait between responses in HA. 

I also wonder if the random connects/disconnects are related to the "cloud MQTT publish" option, even though the newer plug never disconnects on its own. 

(I will not open an issue for my shutters as I have nothing new to add to all the discussions, and every solution has failed so far. All I'm left to do now is change my mesh or my switches for another brand [still trying to decide which will be more laborious], and ask Meross if I have a defective batch.)

Oh, and thank you, krahabb, so much for your work and enthusiasm on this integration.

**Comment by krahabb** [comment]
Hello @mafmafmafmaf,
It looks like your 'newer' devices are set to use only MQTT in their integration configuration page (on HA/meross_lan) and so, if you disable the cloud profile 'MQTT publish' you are basically disabling the possibility to send any command to these devices.
The 12 sec delay is confirming the fact that your device is only using cloud MQTT to communicate.

If the devices are set for 'auto' protocol in meross_lan configuration then you might have an issue reaching the devices over HTTP (but there should be some logs for this...)

Extra-note: the firmware update feature in meross_lan is very 'cheap': it just queries the Meross servers and notifies you of an existing update but I have not enough knowledge to actually implement the firmware update process. Also, being the fw update a risky task I'd rather not mess with it and leave it for the official App.

**Comment by mafmafmafmaf** [comment]
You were so right about some kind of http issue. I found that my wifi router blocks access to port 80 on devices connected to the 2.4-only subnetwork. I will now look on how to solve this, and I hope it also solves the shutter disconnect issue! Thanks for the help, krahabb.

**Comment by mafmafmafmaf** [comment]
Just to close this thread: after another 10 hours or so digging for answers, it all comes to this: beware of the "guest network" in your router if there is no option to expose its devices to the main network. Consumer routers tipically do not have such an option, like my TP-Link 3-unit mesh Deco P9. So this was no issue after all - it was all down to making a correct initial diagnostic!
