### ISSUE TITLE
[MTS200] Displaying cooling instead of heating after 4.4 update

### ISSUE THREAD

**Issue by lukasz-burak** [krahabb/meross_lan#339]
After updating to 4.4 version, termostat seems to report it's cooling instead of heating.
After changing manually to heating, it goes back to cooling after few seconds.
Thermostat works as expected, just reports wrong state for some reason.

Before update it worked just fine.
I'm also attaching screenshot from Meross app that displays proper value.

![IMG_0128](https://github.com/krahabb/meross_lan/assets/25501566/e8494874-d2dc-4214-b7f5-5c3bc77c128a)

![IMG_0129](https://github.com/krahabb/meross_lan/assets/25501566/8e6df109-e51e-4a93-a3c4-d33f6d3e7260)

**Comment by krahabb** [comment]
Hello @lukasz-burak ,
This is a consequence of the new 'SummerMode' feature implemented in these devices and, as stated in the release notes, this is still 'experimental' and (as you're confirming) likely bugged.
I'd need a [diagnostic trace](https://github.com/krahabb/meross_lan/wiki/Diagnostics#download-diagnostics) for your device in order to refine the feature.

Also, since this feature is new I'm not sure all of the MTS200 support this. Is your device expected to support it ? (i.e. can you manage it correctly from the Meross app?)

**Comment by lukasz-burak** [comment]
Attaching diagnostic log, what I did is I changed temperature and than changed in HA from cooling to heating and waited for it to go back to cooling automatically.

Yes, mine MTS200 has this summer mode support in Meross app but I have it switched off since I don't even own any AC unit.
I have the MTS200b version (for underfloor water heating)

[home-assistant_meross_lan_2023-11-24T15-00-36.169Z.log](https://github.com/krahabb/meross_lan/files/13460349/home-assistant_meross_lan_2023-11-24T15-00-36.169Z.log)

**Comment by krahabb** [comment]
That was awesomely fast ;)

...but I need the diagnostic trace that you can download from the device page. Once clicked wait about 10 minutes (while the tracing is in progress) and then the browser should download the file. This only works if you browse locally to your HA instance (no nabucasa nor any proxy/masking)

**Comment by lukasz-burak** [comment]
Oh, sorry for that, here is what you need.
[meross_lan-ffa56b8dde1d711939d17f93a6260b1c-Second Bathroom Thermostat-18f49a10749cca5b419372d8a902b17d.json.txt](https://github.com/krahabb/meross_lan/files/13460936/meross_lan-ffa56b8dde1d711939d17f93a6260b1c-Second.Bathroom.Thermostat-18f49a10749cca5b419372d8a902b17d.json.txt)

**Comment by 3lbart0** [comment]
I have the same issue, volonteer to test any bugfix if needed

**Comment by simille83** [comment]
I also have the same problem, maybe it was better to release a beta version first to test the experimental functions.
