### ISSUE TITLE
Making the actual temperature and the heating a usable entity

### ISSUE THREAD

**Issue by SteffenBMS** [krahabb/meross_lan#340]
Hi all together,

I use and love the Integration of Meross_Lan, thank you so much for it :)
What i would love is, that the actual temperature and the time of heating would be there own entity and unfortunately i´m not capable of creating that. I would love to add the temperature measure by the Meros device to my trends of room temperatures and add the time of heating.
At the moment i can see those data only for each single device if i click to see more details, but not all of them together within in one graph.
Is that possible to add or maybe already possible?

Besides that, thank you so much for adding this easy to use solution.
Best regards
Steffen

![Meros](https://github.com/krahabb/meross_lan/assets/107180409/73ed5549-b6b5-4da7-ad07-4751a2777a56)

**Comment by krahabb** [comment]
Hello @SteffenBMS ,
That chart is provided by the climate entity card in HA and maybe there are some other custom UI cards able to group different climates and show the charts.
You could also use the default HA History dashboard and select your different climates altogether to see their evolution in the same time frame

**Comment by lukasz-burak** [comment]
@SteffenBMS not sure if that would be what you need, but you can create helper template sensors for those values and extract values like that i.e. 
`{{ states.climate.bathroom_thermostat.attributes.current_temperature }}`
I've actually created my template sensor to track combined info when any of my thermostats are ON, it looks like that, maybe it will help you.
`{{  "heating" in [states.climate.office_thermostat.attributes.hvac_action, states.climate.second_bathroom_thermostat.attributes.hvac_action] }}`

**Comment by krahabb** [comment]
The solution suggested by @lukasz-burak looks promising in order to achieve what you need. Nonetheless, this is an issue for HA UI and not strictly related to meross_lan.
I'm cleaning up issues and will close this for not being relevant anymore (unless you might want to move it to a discussion)
