### ISSUE TITLE
Smart outdoor plug MSS620: how do I create device key for this (homekit) device? Or how do I add it to HA?

### ISSUE THREAD

**Issue by maia** [krahabb/meross_lan#342]
I'm trying to add the Meross Smart outdoor plug MSS620 to HA but am failing to do so. The integration detects the plug in the wifi, but I don't have any device key. The Meross iOS app does not display the app. It's properly added to Apple Home.

Steps of attempted installation:
1. reset device until the status led is flashing red slowly
2. connect iOS device to the temporary Wifi, "Meross_SW_xxxx"
3. iOS prompts to add the device to Apple Home and Wifi
4. If I agree, I need to scan the homekit code and then the device is visible in Apple Home. If I don't agree, the device stays in a limbo and is not available anywhere. So I agree.
5. The iOS meross app shows that a new device was found and that it will be added to the home screen within a minute. It is never added and disappears from the list of found devices
6. HA (latest version) sees the Meross plug and prompts for a device key
7. Removing the device from Apple Home does not trigger the HA Homekit integration to suggest adding it to HA. The device simply disappears and nothing else happenes until I reset it.

I hope someone can suggest a way how to add the device to HA. I prefer not having it in Apple Home, using helper switches and Apple Home automations to control it from HA. Thanks!

**Comment by krahabb** [comment]
I was about to reply that likely the procedure was 'temporarily failing' and that adding to the Meross cloud would have finally solved everything ;)

Glad you've already made it
