### ISSUE TITLE
Error requesting the Meross Key

### ISSUE THREAD

**Issue by manmei80** [krahabb/meross_lan#365]
When requesting the merross key, the following error message appears after entering the user name and password :
ConfigEntry.__init__() missing 1 required keyword-only argument: 'minor_version'

**Comment by shark2380** [comment]
Same thing for me.

**Comment by krahabb** [comment]
:( sorry for that..that was a sudden api change...need to fix in a new release or you'd have to downgrade HA

**Comment by xtalkme** [comment]
Thanks posting the changes, adjusted the file locally, can confirm that it works <3
Not sure how smart it was to do it locally, "if it works it ain't stupid" ¯\_(ツ)_/¯

**Comment by krahabb** [comment]
Sadly enough the change is so 'bad' in the HA core api that the [fix](https://github.com/krahabb/meross_lan/commit/f13f1ee4c79eadbd11c2871155463798a999c264) breaks compatibility with previous HA cores so I'm trying some magic to still guarantee meross_lan compatibility with cores back to 2023.7

**Comment by krahabb** [comment]
> Thanks posting the changes, adjusted the file locally, can confirm that it works <3 Not sure how smart it was to do it locally, "if it works it ain't stupid" ¯_(ツ)_/¯

That's fair. When updating with next release it will just be overwritten with the new (hopefully) working implementation. It's going to be more patchy though because of the compatibility layer with previous HA cores (the patch you applied would not work on cores 2023.12 and before)

**Comment by helebrant** [comment]
Hallo,
When requesting the merross key, the following error message appears after entering the user name and password :
404, message='Not Found', url=URL('https://iot.meross.com/v1/Auth/Login')

**Comment by mkaestle** [comment]
Yes, same thing here. When trying to access the Meross Cloud i get the same error message. Additionally I have received an email from Meross regarding technical upgrades and therefore compatibility issues for third party services.

**Comment by krahabb** [comment]
Hello,
This is a totally different issue. We'll see in the next days if it's only a 'temporary down' or if anything changes on the Meross Api infrastructure.
I'll close this since the original issue has been solved.
