### ISSUE TITLE
MSS210 firmware update from 7.1.3 to 7.3.3 breaks energy monitoring

### ISSUE THREAD

**Issue by ohumi** [krahabb/meross_lan#377]
## Version of the custom_component
v4.5.3

## Configuration
N/A - GUI

## Describe the bug
Got 4 MSS210 Hardware 7.0.0
They all came with firmware 7.1.3 and worked perfectly with Meross LAN integration.
Updated one of the smart switches to 7.3.3 and energy monitoring stopped working. Switch function works fine.
All other switches working with firmware 7.1.3 are working just fine.

**Comment by krahabb** [comment]
Maybe they're having the same issue as when the timezone is not set as for other devices ? (see [this](https://github.com/krahabb/meross_lan/issues/367#issuecomment-1882929647))
