### ISSUE TITLE
Smart Cherub Machine media control

### ISSUE THREAD

**Issue by mohkha88** [krahabb/meross_lan#390]
Hi,

since the latest update I can no longer control the media player for my smart cherub machine. Previously I was able to change and turn off the sound. Media player entity is there but no option to change any settings.

**Comment by krahabb** [comment]
Hello @mohkha88,
Which version of meross_lan are you on? During latest development/testing I've seen something has changed in HA and the media player entity (Smart Chreub) started to behave erratically.
So I'm aware the Smart CHerub is not properly working anymore in Cloudy release.
I've then fixed some behaviors in the latest beta's (Moonlight release) so I suggest you to try update to this and see if it works better.
