### ISSUE TITLE
Some localized strings (de) are not there

### ISSUE THREAD

**Issue by MrRickwi** [krahabb/meross_lan#400]
When starting up the Meross LAN integration I see the following error in the HA log:

```
Logger: homeassistant.helpers.translation
Source: helpers/translation.py:288
First occurred: 16:50:27 (1 occurrences)
Last logged: 16:50:27

Validation of translation placeholders for localized (de) string component.meross_lan.issues.cloud_token_expired.fix_flow.step.profile.description failed
```

Possibly there is a missing german translation?

**Comment by PtiBed0** [comment]
Hello, same for (fr)

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:288
First occurred: 18:27:41 (3 occurrences)
Last logged: 18:28:41

Validation of translation placeholders for localized (fr) string component.homeassistant.issues.config_entry_reauth.title failed
Validation of translation placeholders for localized (fr) string component.roborock.config.step.reauth_confirm.title failed
Validation of translation placeholders for localized (fr) string component.meross_lan.issues.cloud_token_expired.fix_flow.step.profile.description failed


issue here => https://github.com/home-assistant/core/issues/111621

**Comment by krahabb** [comment]
Looks like an issue in HA core validation..
I'll leave open for the time being but the official [issure](https://github.com/home-assistant/core/issues/111621) states it is being fixed where it belongs

**Comment by Eoras** [comment]
same problem : last version HAOS : 

` Validation of translation placeholders for localized (fr) string component.homeassistant.issues.config_entry_reauth.title failed`

**Comment by krahabb** [comment]
This issue was referenced and confused with [the one in HA core](https://github.com/home-assistant/core/issues/111621) but they're totally different issues.

Here all of the translations (except EN) were missing the correct string(s)

This has been fixed though in `Moonlight.0.3`
