### ISSUE TITLE
Ignored Meross Matter devices discovered again and again

### ISSUE THREAD

**Issue by sven-debug** [krahabb/meross_lan#405]
Dear krahabb,

I am not sure if this is "in your powers" or a matter of hass. A matter device MSS315 (Smart Plug Mini) is constantly being discovered as a new Meross device although I ignored it multiple times. That device is coupled via Matter and I do not want it in Meross LAN.

Could yu please have a look into the matter? What information do you need to investigate on that?

Best regards
Sven

**Comment by sven-debug** [comment]
Thanks for fixing!

**Comment by krahabb** [comment]
I hope it'll work since I couldn't test a real dhcp scenario so I've just tried test it with some emulated messages.
