### ISSUE TITLE
MSS310 regularly becomes unavailable in HA

### ISSUE THREAD

**Issue by paboman** [krahabb/meross_lan#426]
every few days MSS310 plug becomes unavailable in HA while is online and working good in Meross app and with Alexa.

Once turned on with the app or by alexa the plug become available again in HA

**Comment by krahabb** [comment]
Hello @paboman,
When the device 'falls' offline for whatever reason it tries to reconnect for sure but I guess you don't have a correct ip address configured so, in turn, I think the device is only working when meross_lan receives updates through cloud MQTT.

You could try getting a 'Download diagnostics' for the device/config and post it here so I can better inspect the overall configuration
