### ISSUE TITLE
MTS200 - Show temperature in Celcius

### ISSUE THREAD

**Issue by ricardo-mng** [krahabb/meross_lan#442]
Hi,

I can see that the thermostat card only shows the temperature in Fahrenheit.
![image](https://github.com/krahabb/meross_lan/assets/22666446/8e6e66e6-eb7c-4680-bb66-6dd54ff8403c)

Is there a way to configure it to use in Celcius? I couldn't find anything on the configurations.

I'm new to Home Assistant; sorry if I'm missing something obvious.

Thanks,
Ricardo Gonçalves

**Comment by krahabb** [comment]
I think this is related to the HA general units settings for temperatures (the device in meross_lan has the temp set in Celsius but HA UI can be configured to show either °C or °F).

You can find these global settings in HA under `Settings -> System -> General `

**Comment by ricardo-mng** [comment]
Hi @krahabb, yes, you are right!

Sorry, I'm new on this :)
