### ISSUE TITLE
Cant connect to Meros account on Configuration

### ISSUE THREAD

**Issue by FabianWue** [krahabb/meross_lan#448]
I am trying to to connect my garage door opener with Meross Lan to home assisant. It was succsesfully detectet via dhcp. When i want to configure this device i wanted to connect to my meross account to get the device key. I insertet my correct cerdentials but i am alwas getting an error that a connection is not possible with the message: "ConfigEntry.__init__() missing 1 required keyword-only argument: 'options'" In the app i can connect with those credential without an issue

**Comment by SirMartin** [comment]
Same issue here

**Comment by merewords** [comment]
Same issue here, trying to add multiple different devices, all show the same error when trying to log in to retrieve the device key

**Comment by krahabb** [comment]
Yep...there's an incompatibility in the HA configuration api which was missed by tests.

I think it would work if you 'manually' setup the cloud profile first (not really tested in production but the automatic tests for profile creation are working so I hope this option would 'really' work in the field).
Once configured the cloud profile, the device conf should already automatically pre-fill with the correct device key.

A fix is incoming once I'm able to automate the test for the 'inline' cloud key retrieval.

**Comment by SirMartin** [comment]
It works perfectly, thanks for the effort
