### ISSUE TITLE
Add humidity support to MTS200

### ISSUE THREAD

**Issue by swerb73** [krahabb/meross_lan#459]
Add humidity support to HomeAssistant integration for MTS200 thermostat. Humidity shows up in the Meross app and on the device so if it comes through the integration could we add a humidity entity to support it in HA?

Diagnostic file uploaded.
[meross_lan-56d5af3392b093744ba1ff6e001a66a3-Cabin Living Room-e0d7040ec1004cab7bc62cf576b0c619.json](https://github.com/user-attachments/files/15827572/meross_lan-56d5af3392b093744ba1ff6e001a66a3-Cabin.Living.Room-e0d7040ec1004cab7bc62cf576b0c619.json)

NOTE: It appears this shows up as "humi" in the attached file, and that it is 10x the actual value on the thermostat (I could be wrong here).

**Comment by michbeck100** [comment]
Is this supported on all MTS200 thermostats? I own 6 mts200b thermostats but none of them shows the humidity. Maybe a missing firmware update? There‘s none available, though. 🤔

**Comment by krahabb** [comment]
The trace posted by @swerb73 indicates its device is an `mts200-us` with hw `7.0.0` fw `7.6.7`

**Comment by michbeck100** [comment]
`Appliance.Control.Sensor.Latest` is missing unfortunately, although the hw is `7.0.0` and fw is `7.6.10`. Maybe this will be added in a future fw update.

**Comment by krahabb** [comment]
Since there are a couple of slightly different mts200 on the market (mts200 vs mts200b - eu vs us - boiler/water vs underfloor heating - don't know which is which...) they might have slightly different hw and so we're not sure if the humidity sensor is there or not..also the fw might still not support it for yours.
