### ISSUE TITLE
f-string: unmatched '(' in 5.0.3

### ISSUE THREAD

**Issue by HeikoTietze** [krahabb/meross_lan#477]
After updating to 5.3.0 I get the error in

.../custom_components/meross_lan/helpers/manager.py", line 395
    f"{strftime("%Y-%m-%d_%H-%M-%S", localtime(epoch))}_{self.config_entry_id}.csv"
                 ^
SyntaxError: f-string: unmatched '('

Single quotes for the strftime() solve the issue.

**Comment by krahabb** [comment]
That makes sense...this is working anyway (in linux container) are you maybe using python on windows? or maybe a less recent python ?
I'll make sure this is more robust anyway...
Double checking python docs for f-strings it looks like this should be allowed in python 3.12

**Comment by HeikoTietze** [comment]
Python 3.11.2 on a RasPI running DietPI, which is based on Debian. 

Many thanks for your work!
