### ISSUE TITLE
Garage fan position

### ISSUE THREAD

**Issue by MelleD** [krahabb/meross_lan#481]
**Is your feature request related to a problem? Please describe.**
I have my “Meross Smart WLAN garage door opener”, which has no information about the current position.

What options would I have to implement a fan position for the garage?

I first thought of a time-based cover variant to retrofit the %.
That would be the feature request as to whether it is possible to determine the position in the integration over time.

Something like here: https://github.com/davidramosweb/home-assistant-custom-components-cover-time-based
However, the project looks a little outdated

**Comment by MelleD** [comment]
Okay, I don't think that helps at all because there is no remote stop, so the garage always opens and closes completely anyway.

**Comment by krahabb** [comment]
Yep..it would require a lot of effort and 99% of the times garage doors just open/close to a full run when operated.
