### ISSUE TITLE
Support MS600 presence sensor

### ISSUE THREAD

**Issue by Scrabble3D** [krahabb/meross_lan#488]
https://www.meross.com/en-gc/smart-sensor/matter-presence-sensor/184

[config_entry-meross_lan-992c9fabc96cec25c15f5ded22c528d9.json.txt.gz](https://github.com/user-attachments/files/16958624/config_entry-meross_lan-992c9fabc96cec25c15f5ded22c528d9.json.txt.gz)

The app knows the states Presence and Absence and its duration, also has Moving Away and Minor Motion events in the log. Plus, it measures the illumination in lux (though cannot automatic with this information conditionally).

Would be nice to get more information out of the gadget like zones as knows from similar tools.

**Comment by krahabb** [comment]
This is being tracked in #485
