### ISSUE TITLE
I dont understand how the DHCP works to find my meross hardware

### ISSUE THREAD

**Issue by keteflips** [krahabb/meross_lan#51]
I have a HomeAssistant runing in docker, with network host. 
I installed the Meross Lan integration and I can see it in the integrations.

But after some hours I cant see any Meross bulb I have in my network.

I dont use the HomeAssisntant DHCP, its this the problem?

**Comment by krahabb** [comment]
Hello @keteflips,
I'm definitely a 'docker noob' so I can't really help here except I know my docker development environment doesnt see any dhcp (I've tried to open ports and so but then I've decided to test meross_lan dhcp discovery in my 'production' server which isnt dockerized and it worked).
HomeAssistant 'dhcp' is enabled by default if you have 'default_config' in your configuration else you have to add it (just put a 'dhcp:' line in your configuration.yaml).
Anyway, you can still manually add your devices if you know their address: the dhcp discovery just 'sniffs' this address and proposes an entry to configure but that's it. 
You can manually add your devices like you add an integration (repeat for every device). Just go to the Integrations pane in HA 'Configuration' and 'ADD INTEGRATION', search for 'Meross LAN' and just fill the required informations (address and key, the latter could be left empty and should work anyway see https://github.com/krahabb/meross_lan/issues/35#issuecomment-875732027).
