### ISSUE TITLE
Support the new energy dashboard

### ISSUE THREAD

**Issue by asturale** [krahabb/meross_lan#56]
At the moment it is not possible to select Meross plugs with energy monitoring as consumption devices for the new energy dashboard.

Can you add the "last_reset" attribute to the Energy sensors as described here: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics ?

Thanks!

**Comment by krahabb** [comment]
Ah yeah!
I was expecting this :)
Yesterday I've prepared the patched code and it is 'under test' even if it shouldn't really pose big issues.
I'm going to at least push to #dev asap and maybe release it right after.
I guess there ar ea lot of 'hungry' users out there (me too...I'm 'wasting' so much time playing with the energy integration)

Thank you for opening this: it gives me the option to publish what's going on

**Comment by ctorrao** [comment]
Maybe it also makes sense to convert the unit_of_measurement to kWh instead of Wh, since most of the energy devices are in kWh. Unless the energy dashboard deals correctly with this units, which I don't know yet if it true.
