### ISSUE TITLE
Unable to add devices by HTTP

### ISSUE THREAD

**Issue by silviudc** [krahabb/meross_lan#72]
## Version of the custom_component

2.2.1

## Configuration

```yaml

N/A as it was added my HACS

```

## Describe the bug
I am unable to add/discover devices via HTTP
I have about 12 devices and after installing Meross LAN none are getting auto discovered by dhcp (dhcp is turned on in config.yaml)
If I try to add Meross LAN integration manually it does not give me any option to add by IP just this:

![image](https://user-images.githubusercontent.com/17740184/132321620-e462e04d-966f-480c-a976-70d7ee54c1c2.png)
How can I force discovery/add devices manually for HTTP method?

## Debug log

```text

No errors logged in the logs.

```

**Comment by krahabb** [comment]
Hello @silviudc ,
That one is an 'optional' one shot entry meross_lan configures when you have MQTT integration in your HA. That is for MQTT communication features and actual flow 'forces' you to configure it once.
Just 'submit' it and repeat adding the integration. If you don't have meross devices on your MQTT environment it will be useless and hopefully harmless but you can disable it rightway if it bothers you.

**Comment by silviudc** [comment]
Yes I have mqtt enabled in HA but not for the meross devices, would like to use http in order to not remove them from the cloud app for now.
In that case how can I "discover" devices if not by adding the meross LAN integration on the integrations page?

**Comment by krahabb** [comment]
Yeah, just add the 'MQTT Hub' entry (and forget about it: it will help in the future should you move your devices to MQTT) and then after that, **add meross_lan again for each device**

**Comment by silviudc** [comment]
Yup that did the trick thanks :)

**Comment by patrick-blom** [comment]
> Hello @silviudc , That one is an 'optional' one shot entry meross_lan configures when you have MQTT integration in your HA. That is for MQTT communication features and actual flow 'forces' you to configure it once. Just 'submit' it and repeat adding the integration. If you don't have meross devices on your MQTT environment it will be useless and hopefully harmless but you can disable it rightway if it bothers you.

@krahabb Please add these Information to the Wiki :)

**Comment by krahabb** [comment]
Good point ;)
