### ISSUE TITLE
msg100 not connecting

### ISSUE THREAD

**Issue by ptgomes** [krahabb/meross_lan#75]
Hi. Thanks for the integration.

I have 7 meross devices, and 6 connected using only IP on HA.
One, msg100, cant connect with ip only, and I don't know how to get the device key.

I have all working out fine on Android app.

**Comment by krahabb** [comment]
Hello @ptgomes ,
I'm releasing in few days a feature to recover the 'original' device key from your meross account. If you instead want to give it a try you can follow the manual procedure [here](https://github.com/albertogeniola/MerossIot/wiki/HTTP-APIs) to inquire the meross api and get your own config'ed credentials
This issue #69 is likely similar.

**Comment by mbrihed** [comment]
Hi!
I have the same issue with my two MSG100's. Will sit back and wait for the beta release :-)

**Comment by mbrihed** [comment]
I installed the beta (2.30) and it works like a charm :-) thanks for the great work!

**Comment by ptgomes** [comment]
Just installed v2.3.2, still no joy. Asks por IP (autofills) and key

**Comment by mbrihed** [comment]
Try using "abc123" as the key and then it will take you to the login and once you have logged in it will add the key. That is how I did it.
