### ISSUE TITLE
Confirmation Dialog Feature

### ISSUE THREAD

**Issue by jaytea33** [krahabb/meross_lan#78]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but it would be a nice to have in case the button is inadvertently pressed.

**Describe the solution you'd like**
When pressing Up/Open for devices like the MSG100 smart garage door opener, it would be great to have a confirmation dialog option to prevent the garage door from opening in case the button is inadvertently pressed in the Lovelace UI.

**Describe alternatives you've considered**
An alternative option is to just place the device on a separate Lovelace view to reduce the chance of accidental press when scrolling via the mobile app.

**Comment by krahabb** [comment]
Hello @jaytea33 ,
This really looks like a Lovelace/Frontend feature to look for.
The behaviour of the UI is outside the scope of a component integration like meross_lan is so, if the UI sends commands it just plain executes them with no option to intercept and modify the user interaction (except maybe ignoring the command but how could we detect a command is 'wanted' and not 'unsolicited'?
I guess you can 'isolate' harmful commands/components like opening a (garage)door into a more refined UI panel so to avoid inadvertently click it or maybe direct the question to the HA frontend project where it's maybe being discussed

**Comment by jaytea33** [comment]
Appreciate the point in the right direction, as you were absolutely right. My apologies for bringing the issue here where it didn't belong. I was able to do this with Restrict Card and it's working beautifully:

https://github.com/iantrich/restriction-card
