### ISSUE TITLE
Ms100 Temperature wrong in 2.3.1

### ISSUE THREAD

**Issue by jerrm** [krahabb/meross_lan#85]
Updated from 2.2.1 and the temp from Ms100 reports in the 160's when it should be in the 70's (Fahrenheit). 

Went back to 2.2 1 for now. Will try update again and post logs tonight if not already known issue.

Install/update is through HACS.

**Comment by krahabb** [comment]
Hey @jerrm ,
that's the opposite of what I could expect (I supposed the previous version would have reported wrong values when temperature were to 'transit' to Fahrenheit)

In reality I've re-checked my implementation after your issue and I've found the bug. 

Patch incoming, thank you for quickly signaling

**Comment by CTJohnK** [comment]
I just noticed this as I'm now on 2.3.1.  I have two units and see:
79.5F via Meross app is showing as 175.1F in HA
79.7F via Meross app is showing as 175.5F in HA

It looks like the F is being converted to C, but displayed as F.

**Comment by krahabb** [comment]
Yeah I'm sorry for that: I've refactored sensors code for an upcoming upstream HA core refactoring and messed a bit so now they're double converted :(

**Comment by CTJohnK** [comment]
Installed 2.3.2, restarted HA, temperature is now displaying correctly.
