### ISSUE TITLE
MSS310H appears to be working fine

### ISSUE THREAD

**Issue by almico** [krahabb/meross_lan#9]
If you're interested, I just tested your component with my MSS310H and it works fine.
This is it:
![image](https://user-images.githubusercontent.com/15247405/112029192-43b0f780-8b39-11eb-9bee-1844beef9f13.png)

I'm writing this, just in case you want to create a list of supported devices 😃

**Comment by krahabb** [comment]
Thank you,
I'm opening a discussion for this
